import ebangbangCon from 'events/unknown-start-United States-NY-New York-!!Con.json';
import edotconcatparensparens from 'events/2018-March-Austria-unknown-stateProvince-Salzburg-.concat().json';
import edotNETConfspaceUY from 'events/2017-October-Uruguay-unknown-stateProvince-Montevideo-.NET Conf UY.json';
import e200OK from 'events/1027-June-United States-OK-Tulsa-200OK.json';
import e2017atSwift from 'events/unknown-start-China-unknown-stateProvince-Shenzen-2017@Swift.json';
import e34C3 from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-34C3.json';
import e360iDev from 'events/2015-August-United States-CO-Denver-360iDev.json';
import e44Con from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-44Con.json';
import ecolonclojured from 'events/2018-February-Germany-unknown-stateProvince-Berlin-clojured.json';
import eatdatanativesconf from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-@datanativesconf.json';
import eA2Ydotasm from 'events/2017-September-United States-MI-Ypsilanti-A2Y.asm.json';
import eAccessibilitySummit from 'events/2015-September-United States-TX-NA-Accessibility Summit.json';
import eACE from 'events/unknown-start-Poland-unknown-stateProvince-Krakow-ACE.json';
import eACMCCS from 'events/unknown-start-United States-TX-Dallas-ACM CCS.json';
import eActiveIngredients from 'events/unknown-start-United States-CA-San Francisco-Active Ingredients.json';
import eAdaCamp from 'events/2015-April-Germany-unknown-stateProvince-Berlin-AdaCamp.json';
import eAdobeMAX from 'events/unknown-start-United States-IL-Chicago-Adobe MAX.json';
import eAfricaHackon from 'events/unknown-start-Kenya-unknown-stateProvince-Nairobi-AfricaHackon.json';
import eAgentConference from 'events/2018-January-Austria-unknown-stateProvince-Dornbirn-Agent Conference.json';
import eAgile2015 from 'events/unknown-start-United States-DC-Washington-Agile 2015.json';
import eAgileDevspacePractices from 'events/unknown-start-Germany-unknown-stateProvince-Postdam-Agile Dev Practices.json';
import eAgileIndia from 'events/unknown-start-India-unknown-stateProvince-Bangalore-Agile India.json';
import eAgileSpain from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-Agile Spain.json';
import eAgileTestingspaceDays from 'events/unknown-start-Germany-unknown-stateProvince-Potsdam-Agile Testing Days.json';
import eAIMUtahspaceCIOspaceSummit from 'events/unknown-start-united States-UT-Salt Lake City-AIM Utah CIO Summit.json';
import eAllThingsspaceOpen from 'events/2017-October-United States-NC-Raleigh-All Things Open.json';
import eAllYourspaceBasespaceConf from 'events/2015-November-United Kingdom-unknown-stateProvince-London-All Your Base Conf.json';
import eAlliedMediaspaceConference from 'events/unknown-start-United States-MI-Detroit-Allied Media Conference.json';
import eAlterConf from 'events/unknown-start-United States-OR-Portland-AlterConf.json';
import eAmsterdamJS from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-AmsterdamJS.json';
import eAnEventspaceApart from 'events/2015-August-United States-IL-Chicago-An Event Apart.json';
import eAnDevCon from 'events/2015-December-United States-CA-Santa Clara-AnDevCon.json';
import eAndroidSecurityspaceSymposium from 'events/unknown-start-Austria-unknown-stateProvince-Vienna-Android Security Symposium.json';
import eandyetconf from 'events/2013-October-United States-OR-Portland-andyetconf.json';
import eAngularCamp from 'events/unknown-start-Spain-unknown-stateProvince-Barcelona-Angular Camp.json';
import eAngularCruise from 'events/unknown-start-United States-FL-Miami-Angular Cruise.json';
import eAngularMix from 'events/unknown-start-United States-FL-Orlando-Angular Mix.json';
import eAngularConnect from 'events/2017-November-United Kingdom-unknown-stateProvince-London-AngularConnect.json';
import eAngularUP from 'events/unknown-start-Israel-unknown-stateProvince-Tel Aviv-AngularUP.json';
import eApacheCon from 'events/2015-September-Hungary-unknown-stateProvince-Budapest-ApacheCon.json';
import eAPIStrategy from 'events/2015-November-United States-TX-Austin-API Strategy.json';
import eAPIWorld from 'events/2015-September-United States-CA-Santa Clara-API World.json';
import eAPIdays from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-APIdays.json';
import eAPIdays from 'events/unknown-start-United States-CA-San Francisco-APIdays.json';
import eAppBuildersspaceSwitzerland from 'events/unknown-start-Switzerland-unknown-stateProvince-Lausanne-App Builders Switzerland.json';
import eAppDesignspaceandspaceDevelopmentspaceConference from 'events/unknown-start-Spain-unknown-stateProvince-Barcelona-App Design & Development Conference.json';
import eAppdevcon2017 from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-Appdevcon 2017.json';
import eArtifactConference from 'events/2014-September-United States-RI-Province-Artifact Conference.json';
import easiabsdcon from 'events/2015-March-Japan-unknown-stateProvince-Tokyo-asiabsdcon.json';
import eAtlassianSummit from 'events/2015-November-United States-CA-San Francisco-Atlassian Summit.json';
import eAtlSecCon from 'events/unknown-start-Canada-Nova Scotia-Halifax-AtlSecCon.json';
import eATypI from 'events/unknown-start-Brazil-unknown-stateProvince-Sao Paulo-ATypI.json';
import eAUSTINGAMEspaceCONFERENCE from 'events/2017-September-United States-TX-Austin-AUSTIN GAME CONFERENCE.json';
import eAVAR from 'events/unknown-start-China-unknown-stateProvince-Bejing-AVAR.json';
import eAWSRecolonInvent from 'events/unknown-start-unknown-country-unknown-stateProvince-unknown-city-AWS ReInvent.json';
import eAWSrecoloninvent from 'events/2015-October-United States-NV-Las Vegas-AWS reinvent.json';
import eBackboneConf from 'events/2014-December-United States-MA-Boston-BackboneConf.json';
import eBADCamp from 'events/2015-October-United States-CA-Berkeley-BADCamp.json';
import eBASTAbang from 'events/unknown-start-Germany-unknown-stateProvince-Mainz-BASTA!.json';
import eBeyondTellerrand from 'events/unknown-start-Germany-unknown-stateProvince-Düsseldorf-Beyond Tellerrand.json';
import eBeyondThespaceDesktop from 'events/2015-October-United States-unknown-stateProvince-Washington DC-Beyond The Desktop.json';
import eBI2015 from 'events/unknown-start-France-unknown-stateProvince-Nice-BI2015.json';
import eBigDataspaceConference from 'events/unknown-start-India-unknown-stateProvince-Hyderabad-Big Data Conference.json';
import eBigDataspaceConference from 'events/2014-September-United States-CA-Santa Clara-Big Data Conference.json';
import eBigDesignspaceConference from 'events/2014-September-United States-TX-Addison-Big Design Conference.json';
import eBigRubyspaceConf from 'events/unknown-start-United States-TX-Dallas-Big Ruby Conf.json';
import eBigConf from 'events/2015-March-United States-MD-Silver Spring-BigConf.json';
import eBlackHat from 'events/unknown-start-United States-NV-Las Vegas-Black Hat.json';
import eBlackHatAsia from 'events/unknown-start-Singapore-unknown-stateProvince-Singapore-BlackHat Asia.json';
import eBlackHatEU from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-BlackHat EU.json';
import eBlackHatUS from 'events/unknown-start-United States-NV-Las Vegas-BlackHat US.json';
import eBlendConference from 'events/2014-September-United States-NC-Charlotte-Blend Conference.json';
import eBlendWebspaceMix from 'events/unknown-start-France-unknown-stateProvince-Lyon-Blend Web Mix.json';
import eBlockchainandspaceCryptocurrencyspaceConspace2018 from 'events/2018-February-USA-Texas-Dallas-Blockchain & Cryptocurrency Con 2018.json';
import eBooksinspaceBrowsers from 'events/2014-October-United States-CA-San Francisco-Books in Browsers.json';
import eboostparensjsparens from 'events/unknown-start-Israel-unknown-stateProvince-Tel Aviv-boost(js).json';
import eBooster from 'events/unknown-start-Norway-unknown-stateProvince-Bergen-Booster.json';
import eBornhack from 'events/unknown-start-Denmark-unknown-stateProvince-Bornholm-Bornhack.json';
import eBostonCodespaceCamp from 'events/2017-November-USA-MA-Burlington-Boston Code Camp.json';
import eBotConf from 'events/unknown-start-France-unknown-stateProvince-Montpellier-BotConf.json';
import eBoxWorks from 'events/2014-September-United States-CA-San Francisco-BoxWorks.json';
import eBrazilJSspaceConf from 'events/2014-August-Rio de Janerio-unknown-stateProvince-Rio de Janerio-Brazil JS Conf.json';
import eBrazilJS from 'events/unknown-start-Brazil-unknown-stateProvince-Porto Alegre-BrazilJS.json';
import eBrick2014 from 'events/2015-October-United Kingdom-unknown-stateProvince-Birmingham-Brick 2014.json';
import eBritishnodespaceconf from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-British node conf.json';
import eBrooklynJS from 'events/2015-September-United States-NY-Brooklyn-BrooklynJS.json';
import eBruCon from 'events/unknown-start-Belgium-unknown-stateProvince-Bruxelles-BruCon.json';
import ebsdcan from 'events/2015-June-Canada-ON-Ottawa-bsdcan.json';
import eBSidesCanberra from 'events/unknown-start-Australia-unknown-stateProvince-Canberra-BSides Canberra.json';
import eBSidesLjubljana from 'events/unknown-start-Slovenia-unknown-stateProvince-Ljubljana-BSidesLjubljana.json';
import eBSidesMunichatBSidesMunich from 'events/unknown-start-Germany-unknown-stateProvince-Munich-BSidesMunich @BSidesMunich.json';
import eBudapestNodeConfspace2017 from 'events/unknown-start-Hungary-unknown-stateProvince-Budapest-Budapest NodeConf 2017.json';
import eBuildstufflithuania from 'events/unknown-start-Lithuania-unknown-stateProvince-unknown-city-Buildstuff lithuania.json';
import eBulgariaWebspaceSummit from 'events/unknown-start-Bulgaria-unknown-stateProvince-Sofia-Bulgaria Web Summit.json';
import eBusinessofspaceSoftwarespaceConference from 'events/2017-September-United States-MA-Boston-Business of Software Conference.json';
import eBuzzJS from 'events/2017-October-United States-FL-West Palm Beach-BuzzJS.json';
import eBytesConf from 'events/2017-November-England-East Sussex-Brighton-Bytes Conf.json';
import eCakeFest from 'events/2015-May-United States-NY-New York-CakeFest.json';
import eCAMPFestival from 'events/2015-September-Canada-AB-Calgary-CAMP Festival.json';
import eCampJS from 'events/2015-November-Australia-unknown-stateProvince-Springbrook-CampJS.json';
import eCanSecWest from 'events/unknown-start-Canada-BC-Vancouver-CanSecWest.json';
import ecanvas from 'events/unknown-start-United Kingdom-unknown-stateProvince-Birmingham-canvas.json';
import eCapitolJS from 'events/unknown-start-United States-VA-Arlington-CapitolJS.json';
import eCardis from 'events/unknown-start-Switzerland-unknown-stateProvince-Lugano-Cardis.json';
import eCARO from 'events/unknown-start-Poland-unknown-stateProvince-Krakow-CARO.json';
import eCascadiaFest from 'events/unknown-start-United States-DC-Washington-CascadiaFest.json';
import eCascadiaJS from 'events/2014-July-United States-OR-Portland-CascadiaJS.json';
import eCasITConf from 'events/unknown-start-United States-WA-Seattle-CasITConf.json';
import eCassandraSummit from 'events/2015-October-United Kingdom-unknown-stateProvince-London-Cassandra Summit.json';
import eCentralWisconsinspaceITspaceConference from 'events/2017-September-USA-WI-Stevens Point-Central Wisconsin IT Conference.json';
import eChainReactspace2017 from 'events/2017-July-United States-OR-Portland-Chain React 2017.json';
import eChefConf from 'events/2015-July-United States-TX-Austin-ChefConf.json';
import eCHES from 'events/unknown-start-Taiwan-unknown-stateProvince-Taipei City-CHES.json';
import eChippewaValleyspaceCodespaceCamp from 'events/2017-November-United States-WI-Eau Clair-Chippewa Valley Code Camp.json';
import eChromeDevspaceSummitspace2017 from 'events/unknown-start-United States-CA-San Francisco-Chrome Dev Summit 2017.json';
import eCircleCityCon from 'events/unknown-start-United States-IN-Indianapolis-CircleCityCon.json';
import eCircumventionTechspaceFestival from 'events/2015-March-Spain-unknown-stateProvince-Valencia-Circumvention Tech Festival.json';
import eClarity from 'events/2017-November-USA-California-San Francisco-Clarity.json';
import eClojurefwslashWest from 'events/2015-April-United States-OR-Portland-ClojureWest.json';
import eCloudExpo from 'events/2015-November-United States-CA-Santa Clara-Cloud Expo.json';
import eCloudBrew2017 from 'events/2017-November-Belgium-Antwerp-Mechelen-CloudBrew 2017.json';
import eCloudDevelopConf from 'events/2015-October-United States-OH-Columbus-CloudDevelop Conf.json';
import eCloudPlugFest from 'events/2015-September-United States-CA-Santa Clara-CloudPlugFest.json';
import eCMXSummit from 'events/2015-October-United States-CA-San Francisco-CMX Summit.json';
import eCocoaLove from 'events/2015-October-United States-PA-Philadelphia-Cocoa Love.json';
import eCocoaConf from 'events/2015-September-United States-MA-Boston-CocoaConf.json';
import eCocoaConfChicagospace2017 from 'events/unknown-start-United States-IL-Chicago-CocoaConf Chicago 2017.json';
import eCocoaLove from 'events/unknown-start-United States-PA-Philadelphia-CocoaLove.json';
import eCode from 'events/unknown-start-Australia-unknown-stateProvince-Brisbane-Code.json';
import eCodeMotion from 'events/2015-December-Israel-unknown-stateProvince-Rishon LeZion-Code Motion.json';
import eCodeonspacethespaceBeach from 'events/unknown-start-United States-FL-Jacksonville-Code on the Beach.json';
import eCodePaLOUsa from 'events/2015-April-United States-KY-Louisville-Code PaLOUsa.json';
import eCodebits from 'events/2014-April-Portugal-unknown-stateProvince-Lisbon-Codebits.json';
import eCodemania from 'events/unknown-start-New Zealand-unknown-stateProvince-Auckland-Codemania.json';
import eCodeMash from 'events/2018-January-United States-OH-Sandusky-CodeMash.json';
import eCodemotion from 'events/unknown-start-Italy-unknown-stateProvince-Rome-Codemotion.json';
import eCodemotion from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-Codemotion.json';
import eCodePaLOUsa from 'events/unknown-start-United States-KY-Louisville-CodePaLOUsa.json';
import eCoderCruise from 'events/unknown-start-United States-LA-New Orlean-Coder Cruise.json';
import eCodestock from 'events/2018-April-United States-TN-Knoxville-Codestock.json';
import eColdFront from 'events/unknown-start-Denmark-unknown-stateProvince-Copenhagen-ColdFront.json';
import ecoldfrontconf from 'events/2015-September-Denmark-unknown-stateProvince-Copenhagen-coldfrontconf.json';
import eCollisionConf from 'events/2015-April-United States-LA-New Orleans-Collision Conf.json';
import eCommunityLeadershipspaceSummit from 'events/2015-July-United States-OR-Portland-Community Leadership Summit.json';
import eConfabIntensive from 'events/unknown-start-United States-OR-Portland-Confab Intensive.json';
import eConferenceforspacethespaceAssociationspaceofspaceSoftwarespaceTesting from 'events/unknown-start-United States-MI-Grand Rapids-Conference for the Association of Software Testing.json';
import eConfidence from 'events/unknown-start-Poland-unknown-stateProvince-Krakow-Confidence.json';
import eConfitura from 'events/2015-July-Poland-unknown-stateProvince-Warsaw-Confitura.json';
import eConFooMontreal from 'events/2018-March-Canada-unknown-stateProvince-Montreal-ConFoo Montreal.json';
import eConFooVancouver from 'events/unknown-start-Canada-BC-Vancouver-ConFoo Vancouver.json';
import eCONFRONT from 'events/unknown-start-Sweden-unknown-stateProvince-Malmö-CONFRONT.json';
import eConnectdotjs from 'events/2015-October-United States-GA-Atlanta-Connect.js.json';
import eConnectdotTech from 'events/2017-September-United States-GA-Atlanta-Connect.Tech.json';
import eConnections from 'events/2015-June-United States-NY-New York-Connections.json';
import eConnectJS from 'events/unknown-start-United States-GA-Atlanta-ConnectJS.json';
import eContainerCamp from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-ContainerCamp.json';
import eContinuousLifecyclespaceConference from 'events/unknown-start-Germany-unknown-stateProvince-Mannheim-Continuous Lifecycle Conference.json';
import eConvergeSE from 'events/unknown-start-United States-SC-Columbia-Converge SE.json';
import eCopenhagenContext from 'events/unknown-start-Denmark-unknown-stateProvince-Copenhagen-Copenhagen Context.json';
import ecopenhagenjs from 'events/2015-October-Denmark-unknown-stateProvince-Copenhagen-copenhagenjs.json';
import eCornerstone from 'events/2015-May-United States-CA-San Diego-Cornerstone.json';
import eCouchbaseLive from 'events/2015-April-United Kingdom-unknown-stateProvince-London-Couchbase Live.json';
import ecppcon from 'events/2015-September-United States-WA-Bellevue-cppcon.json';
import eCraftConference from 'events/unknown-start-Hungary-unknown-stateProvince-Budapest-Craft Conference.json';
import eCreateUpstate from 'events/2015-April-United States-NY-Syracuse-Create Upstate.json';
import eCrikeyCon from 'events/unknown-start-Australia-unknown-stateProvince-Brisbane-CrikeyCon.json';
import eCSSDay from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-CSS Day.json';
import eCSSDevspaceConf from 'events/2017-October-United States-LA-New Orleans-CSS Dev Conf.json';
import eCSSMinskdashJSConf from 'events/unknown-start-Belarus-unknown-stateProvince-Minsk-CSS-Minsk-JS Conf.json';
import ecssfwslashsassconference from 'events/unknown-start-unknown-country-unknown-stateProvince-unknown-city-csssass conference.json';
import eCSSConf from 'events/2015-September-Germany-unknown-stateProvince-Berlin-CSSConf.json';
import eCSSConf from 'events/unknown-start-United States-FL-Miami-CSSConf.json';
import eCSSConfAU from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-CSSConf AU.json';
import eCSSConfAustralia from 'events/2015-March-Australia-unknown-stateProvince-Melbourne-CSSConf Australia.json';
import eCSSConfBudapest from 'events/unknown-start-Hungary-unknown-stateProvince-Budapest-CSSConf Budapest.json';
import eCSVConf from 'events/2014-July-Germany-unknown-stateProvince-Berlin-CSVConf.json';
import eCukeUp from 'events/2014-April-United Kingdom-unknown-stateProvince-London-CukeUp.json';
import eDaFED from 'events/unknown-start-Serbia-unknown-stateProvince-Novi Sad-DaFED.json';
import eDataDayspaceTexasspace? from 'events/2016-January-United States-TX-Austin-Data Day Texas.json';
import edConstruct from 'events/unknown-start-United Kingdom-unknown-stateProvince-Brighton-dConstruct.json';
import eDecolonCode from 'events/unknown-start-Japan-unknown-stateProvince-Tokyo-DeCode.json';
import eDeeperLifespaceHolidayspaceschool from 'events/unknown-start-Nigeria-unknown-stateProvince-Lagos-Deeper Life Holiday school.json';
import eDeepSec from 'events/unknown-start-Austria-unknown-stateProvince-Vienna-DeepSec.json';
import eDefCamp from 'events/unknown-start-Romania-unknown-stateProvince-Bucharest-DefCamp.json';
import eDEFCON from 'events/2016-August-United States-NV-Las Vegas-DEFCON.json';
import eDenverDevspaceDay from 'events/unknown-start-United States-CO-Denver-Denver Dev Day.json';
import eDesertCodespaceCamp from 'events/2017-October-United States-AZ-Chandler-Desert Code Camp.json';
import eDesignerofspaceThings from 'events/2015-December-United States-CA-San Jose-Designer of Things.json';
import eDeSymfony from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-DeSymfony.json';
import eDevConf from 'events/2016-February-Czech Republic-unknown-stateProvince-Brno-DevConf.json';
import eDevConnections from 'events/unknown-start-United States-NV-Las Vegas-DevConnections.json';
import eDevDay from 'events/unknown-start-Poland-unknown-stateProvince-Poland-DevDay.json';
import eDeveloperWeekspaceConf from 'events/2016-February-United States-CA-San Francisco-Developer Week Conf.json';
import eDeveloperWeekJavaScriptspaceConference from 'events/unknown-start-United States-CA-San Francisco-DeveloperWeek JavaScript Conference.json';
import eDevExperiencedotro from 'events/unknown-start-Romania-unknown-stateProvince-Iasi-DevExperience.ro.json';
import eDevIntersection from 'events/unknown-start-unknown-country-unknown-stateProvince-unknown-city-DevIntersection.json';
import eDEVitWebspaceConference from 'events/unknown-start-Greece-unknown-stateProvince-Thessaloniki-DEVit Web Conference.json';
import edevLink from 'events/2014-August-United States-TN-Chattanooga-devLink.json';
import eDevNexus from 'events/unknown-start-United States-GA-Atlanta-DevNexus.json';
import eDevOpsDays from 'events/2015-September-India-unknown-stateProvince-Bangalore-DevOpsDays.json';
import eDevopsDays from 'events/unknown-start-United States-IL-Chicago-DevopsDays.json';
import eDevopsDays from 'events/unknown-start-United States-MN-Minneapolis-DevopsDays.json';
import eDevoxxBE from 'events/2015-November-Belgium-unknown-stateProvince-Antwerp-Devoxx BE.json';
import eDevoxxMA from 'events/unknown-start-Morocco-unknown-stateProvince-Casablanca-Devoxx MA.json';
import eDevoxxPL from 'events/unknown-start-Poland-unknown-stateProvince-Krakow-Devoxx PL.json';
import eDevoxxUK from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Devoxx UK.json';
import eDevRelCon from 'events/2015-September-United Kingdom-unknown-stateProvince-London-DevRelCon.json';
import eDevsLobespaceBaconspace2014 from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Devs Lobe Bacon 2014.json';
import eDevSpace from 'events/2017-October-United States-AL-Huntsville-DevSpace.json';
import eDevSum from 'events/unknown-start-Sweden-unknown-stateProvince-Stockholm-DevSum.json';
import eDevUp from 'events/2017-October-United States-MO-St. Louis-DevUp.json';
import eDevWeek from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-DevWeek.json';
import edevworld from 'events/2015-August-Australia-unknown-stateProvince-Melbourne-devworld.json';
import eDigitalBookspaceWorld from 'events/2015-March-United States-NY-New York-Digital Book World.json';
import eDIMVA from 'events/unknown-start-Germany-unknown-stateProvince-Bonn-DIMVA.json';
import eDinosaurjs from 'events/unknown-start-United States-CO-Denver-Dinosaurjs.json';
import eDisruptSF from 'events/2014-September-United States-CA-San Francisco-Disrupt SF.json';
import eDistill from 'events/2014-August-United States-CA-San Francisco-Distill.json';
import eDistill2014 from 'events/unknown-start-United States-CA-San Francisco-Distill 2014.json';
import eDjangoCon from 'events/unknown-start-United Kingdom-Wales-Cardiff-DjangoCon.json';
import eDjangoCon from 'events/2015-September-United States-TX-Austin-DjangoCon.json';
import eDjangoConEurope from 'events/unknown-start-United Kingdom-Wales-Cardiff-DjangoCon Europe.json';
import eDjangoVillage from 'events/2014-June-Italy-unknown-stateProvince-Orvieto-DjangoVillage.json';
import eDLDConference from 'events/2015-January-Germany-unknown-stateProvince-Munich-DLD Conference.json';
import eDNNSummit from 'events/2018-February-United States-CO-Denver-DNN Summit.json';
import eDockerCon from 'events/2015-November-Spain-unknown-stateProvince-Barcelona-DockerCon.json';
import eDogFoodCon from 'events/2017-October-United States-OH-Columbus-DogFood Con.json';
import eDotAll from 'events/2017-October-United States-OR-Portland-Dot All.json';
import edotswift from 'events/2015-February-France-unknown-stateProvince-Paris-dot swift.json';
import edotCSS from 'events/unknown-start-France-unknown-stateProvince-Paris-dotCSS.json';
import edotGo from 'events/2015-November-France-unknown-stateProvince-Paris-dotGo.json';
import edotJS from 'events/unknown-start-France-unknown-stateProvince-Paris-dotJS.json';
import edotScale from 'events/2015-June-France-unknown-stateProvince-Paris-dotScale.json';
import edotSwift from 'events/2016-January-France-unknown-stateProvince-Paris-dotSwift.json';
import eDreamforce from 'events/2015-September-United States-CA-San Francisco-Dreamforce.json';
import eDroidcon from 'events/2015-November-France-unknown-stateProvince-Paris-Droidcon.json';
import eDroidconLondon from 'events/2017-October-England-unknown-stateProvince-London-Droidcon London.json';
import eDroidconNYC from 'events/2017-September-US-NY-New York-Droidcon NYC.json';
import eDroidconSF from 'events/2017-November-US-CA-San Francisco-Droidcon SF.json';
import eDroidconStockholm from 'events/unknown-start-Sweden-unknown-stateProvince-Stockholm-Droidcon Stockholm.json';
import eDrupalCamp from 'events/unknown-start-Scotland-unknown-stateProvince-Edinburgh-DrupalCamp.json';
import eDrupalCon from 'events/unknown-start-Czech Republic-unknown-stateProvince-Prague-DrupalCon.json';
import eDrupalCon from 'events/2015-September-Spain-unknown-stateProvince-Barcelona-DrupalCon.json';
import eDrupalCon from 'events/unknown-start-United States-CA-Long Beach-DrupalCon.json';
import eDutchPHPspaceConference from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-Dutch PHP Conference.json';
import eeSAMEdashspaceCTFspaceonspaceNovspace30 from 'events/unknown-start-France-unknown-stateProvince-Sophia Antipolis-e-SAME - CTF on Nov 30.json';
import eEARLparensEffectivespaceApplicationsspaceofspaceRspaceLanguageparens from 'events/2015-September-United Kingdom-unknown-stateProvince-London-EARL (Effective Applications of R Language).json';
import eebookcraft from 'events/2016-March-Canada-ON-Toronto-ebookcraft.json';
import eEclipseCon from 'events/2015-November-Germany-unknown-stateProvince-Ludwigsberg-EclipseCon.json';
import eEclipseCon from 'events/unknown-start-United States-CA-San Francisco-EclipseCon.json';
import eeCrime from 'events/unknown-start-United States-AZ-Scottdale-eCrime.json';
import eEdgeConference from 'events/2015-June-United Kingdom-unknown-stateProvince-London-Edge Conference.json';
import eEdgeConf from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-EdgeConf.json';
import eEICAR from 'events/unknown-start-unknown-country-unknown-stateProvince-unknown-city-EICAR.json';
import eElementsPennspaceState from 'events/unknown-start-United States-PA-State College-Elements Penn State.json';
import eElixirwithspaceLove from 'events/2017-November-USA-RI-Providence-Elixir with Love.json';
import eElixirConf from 'events/2015-October-United States-TX-Austin-ElixirConf.json';
import eEmberFest from 'events/2015-September-United Kingdom-unknown-stateProvince-Cambridge-Ember Fest.json';
import eEmberConf from 'events/2015-March-United States-OR-Portland-EmberConf.json';
import eEmberFest from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-EmberFest.json';
import eEmpireConf from 'events/unknown-start-United States-NY-New York-Empire Conf.json';
import eEmpireNode from 'events/2015-October-United States-NY-New York-Empire Node.json';
import eEmpireJS from 'events/2015-April-United States-NY-New York-EmpireJS.json';
import eEmpireNode from 'events/unknown-start-United States-NY-New York-EmpireNode.json';
import eEndpoint from 'events/2015-September-The Netherlands-unknown-stateProvince-Amsterdam-Endpoint.json';
import eENIGMA from 'events/unknown-start-United States-CA-Oakland-ENIGMA.json';
import eEnterJS from 'events/unknown-start-Germany-unknown-stateProvince-Darmstadt-EnterJS.json';
import eEpicFEL from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Epic FEL.json';
import eErlangConference from 'events/2015-June-Sweden-unknown-stateProvince-Stockholm-Erlang Conference.json';
import eESORICS from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-ESORICS.json';
import eEuroBSDcon from 'events/2015-October-Bulgaria-unknown-stateProvince-Sofia-EuroBSDcon.json';
import eEurocrypt from 'events/unknown-start-France-unknown-stateProvince-Paris-Eurocrypt.json';
import eEuroIA2014 from 'events/2014-September-Poland-unknown-stateProvince-NA-EuroIA 2014.json';
import eEuroPython from 'events/2015-July-Spain-unknown-stateProvince-Bilbao-EuroPython.json';
import eEuRuKo from 'events/unknown-start-Austria-unknown-stateProvince-Salzburg-EuRuKo.json';
import eEuRuKo from 'events/2014-June-Ukraine-unknown-stateProvince-Kiev-EuRuKo.json';
import eEvernoteConference from 'events/2014-October-United States-CA-San Francisco-Evernote Conference.json';
import eExtensibleWebspaceSummit from 'events/2014-September-Germany-unknown-stateProvince-Berlin-Extensible Web Summit.json';
import eF5Festival from 'events/unknown-start-unknown-country-unknown-stateProvince-unknown-city-F5 Festival.json';
import eF8 from 'events/2015-May-United States-CA-San Francisco-F8.json';
import eFailCon from 'events/2015-October-Brazil-unknown-stateProvince-Porto Alegre-FailCon.json';
import eFalsyValues from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-Falsy Values.json';
import effconf from 'events/unknown-start-United Kingdom-unknown-stateProvince-Brighton-ffconf.json';
import eFIRSTFare from 'events/unknown-start-United States-OR-Portland-FIRSTFare.json';
import eFISL from 'events/2015-July-Brazil-unknown-stateProvince-Porto Alegre-FISL.json';
import eFITC from 'events/unknown-start-Canada-unknown-stateProvince-Toronto-FITC.json';
import eFlight from 'events/2015-October-United States-CA-San Francisco-Flight.json';
import eFlossSpringspace2014 from 'events/2014-March-United Kingdom-unknown-stateProvince-Brighton-Floss Spring 2014.json';
import eFluent from 'events/2015-April-United States-CA-San Francisco-Fluent.json';
import eFormFunctionspaceandspaceClassspace8 from 'events/unknown-start-Philippines-unknown-stateProvince-Manila-Form Function & Class 8.json';
import eForwardJS from 'events/unknown-start-United States-CA-San Francisco-Forward JS.json';
import eForwardSwift from 'events/unknown-start-United States-CA-San Francisco-Forward Swift.json';
import eForwardJS from 'events/unknown-start-United States-CA-San Francisco-ForwardJS.json';
import eFOSDEM from 'events/2016-January-Belgium-unknown-stateProvince-Brussels-FOSDEM.json';
import eFOSS4G from 'events/2015-September-South Korea-unknown-stateProvince-SEOUL-FOSS4G.json';
import eFOSSETCON from 'events/2015-November-United States-FL-Orlando-FOSSETCON.json';
import eFOWD from 'events/unknown-start-unknown-country-unknown-stateProvince-unknown-city-FOWD.json';
import eFrankfurtBookfair from 'events/2015-October-Germany-unknown-stateProvince-Frankfurt-Frankfurt Bookfair.json';
import eFrenchKit from 'events/unknown-start-France-unknown-stateProvince-Paris-FrenchKit.json';
import eFrontEndspaceDesignspaceConference from 'events/2018-April-United States-FL-St. Petersburg-Front End Design Conference.json';
import eFrontEndspaceDesignspaceConference from 'events/unknown-start-United States-FL-St.Petersburg-Front End Design Conference.json';
import eFrontinspaceBH from 'events/unknown-start-Brazil-Minas Gerais-Belo Horizonte-Front in BH.json';
import eFrontPorch from 'events/2015-October-United States-TX-Dallas-Front Porch.json';
import eFrontTrends from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-Front Trends.json';
import eFrontEndCarioca from 'events/2015-September-Brazil-unknown-stateProvince-Rio de Janiero-Front-End Carioca.json';
import efrontendconference from 'events/unknown-start-Switzerland-unknown-stateProvince-Zurich-front-end conference.json';
import eFrontEndConference from 'events/2015-May-United States-FL-St.Petersburg-Front-End Conference.json';
import eFrontTrends from 'events/2018-May-Poland-unknown-stateProvince-Warsaw-Front-Trends.json';
import eFronteers2014 from 'events/2014-October-The Netherlands-unknown-stateProvince-Amsterdam-Fronteers 2014.json';
import eFronteersConference from 'events/2015-October-The Netherlands-unknown-stateProvince-Amsterdam-Fronteers Conference.json';
import eFRONTENDCONspace2017 from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-FRONTEND CON 2017.json';
import eFrontendConferencespaceZurich from 'events/unknown-start-Switzerland-unknown-stateProvince-Zurich-Frontend Conference Zurich.json';
import eFrontendDevspaceConfspace2017 from 'events/unknown-start-Belarus-unknown-stateProvince-Minsk-Frontend Dev Conf 2017.json';
import eFrontendNE from 'events/2018-April-United Kingdom-unknown-stateProvince-Newcastle Upon Tyne-Frontend NE.json';
import eFrontendUnited from 'events/unknown-start-Greece-unknown-stateProvince-Athens-Frontend United.json';
import eFrontenders from 'events/unknown-start-Spain-unknown-stateProvince-Valencia-Frontenders.json';
import eFrontFest from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-FrontFest.json';
import eFrontInterior from 'events/2014-August-Brazil-unknown-stateProvince-Ijui-FrontInterior.json';
import eFrontTalks from 'events/unknown-start-Russia-unknown-stateProvince-Ekaterinburg-FrontTalks.json';
import eFrOSCon from 'events/2015-August-Germany-unknown-stateProvince-Sankt Augustin-FrOSCon.json';
import eFrozenRails from 'events/2014-September-Finland-unknown-stateProvince-Helsinki-Frozen Rails.json';
import eFullFrontal from 'events/2015-November-United Kingdom-unknown-stateProvince-Brighton-Full Frontal.json';
import eFullStackspaceConf from 'events/unknown-start-Spain-unknown-stateProvince-Barcelona-Full Stack Conf.json';
import eFullStackspaceConf from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Full Stack Conf.json';
import eFullStackspaceFest from 'events/unknown-start-Spain-unknown-stateProvince-Barcelona-Full Stack Fest.json';
import eFullStackspaceToronto from 'events/unknown-start-Canada-ON-Toronto-Full Stack Toronto.json';
import eFullStack from 'events/2014-October-United Kingdom-unknown-stateProvince-London-FullStack.json';
import eFunctionalConfspaceIndia from 'events/unknown-start-India-unknown-stateProvince-Bangalore-Functional Conf India.json';
import eFunctionalSwiftspaceConferencespace2017 from 'events/unknown-start-United States-NY-Brooklyn-Functional Swift Conference 2017.json';
import eFunctions17 from 'events/unknown-start-Canada-ON-Toronto-Functions17.json';
import eFutureInsights from 'events/2015-June-United States-NV-Las Vegas-Future Insights.json';
import eFutureJS from 'events/2015-September-Spain-unknown-stateProvince-Barcelona-Future JS.json';
import eFutureofspaceWebspaceApps from 'events/2015-October-United Kingdom-unknown-stateProvince-London-Future of Web Apps.json';
import eFutureofspaceWebspaceApps from 'events/unknown-start-United States-MA-Boston-Future of Web Apps.json';
import eFutureofspaceWebspaceDesign from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Future of Web Design.json';
import eFutureofspaceWebspaceDesignspaceparensthespaceBreweryparens from 'events/2015-April-United Kingdom-unknown-stateProvince-London-Future of Web Design (the Brewery).json';
import eFutureStack from 'events/2015-November-United States-CA-San Francisco-FutureStack.json';
import eGameDevelopersspaceConference from 'events/2018-March-United States-CA-San Francisco-Game Developers Conference.json';
import eGartnerApplicationspaceArchitecture from 'events/2015-December-United States-NV-Las Vegas-Gartner Application Architecture.json';
import eGDC from 'events/unknown-start-China-unknown-stateProvince-Shanghai-GDC.json';
import eGDC from 'events/unknown-start-United States-CA-San Francisco-GDC.json';
import eGDCChina from 'events/unknown-start-China-unknown-stateProvince-Beijing-GDC China.json';
import eGDCNext from 'events/2016-March-United States-CA-San Francisco-GDC Next.json';
import eGeeCON from 'events/2015-October-Czech Republic-unknown-stateProvince-Prague-GeeCON.json';
import eGeekGirlCamp from 'events/unknown-start-United States-VA-Charlotte-GeekGirlCamp.json';
import eGGDevCon from 'events/2016-July-United States-CA-San Jose-GGDevCon.json';
import eGIDS from 'events/unknown-start-India-unknown-stateProvince-Bangalore-GIDS.json';
import eGlobalInnovationspaceForum from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Global Innovation Forum.json';
import eGluecon from 'events/2015-May-United States-CO-Denver-Gluecon.json';
import eGoGaRuCo from 'events/2014-September-United States-CA-San Francisco-GoGaRuCo.json';
import eGoogleIfwslashO from 'events/2014-June-United States-CA-San Francisco-Google IO.json';
import eGoogleTestspaceAutomation from 'events/2015-November-United States-VA-Cambridge-Google Test Automation.json';
import eGopherCon from 'events/2015-July-United States-CO-Denver-GopherCon.json';
import eGoto from 'events/unknown-start-Denmark-unknown-stateProvince-Copenhagen-Goto.json';
import eGOTO from 'events/2015-September-United Kingdom-unknown-stateProvince-London-GOTO.json';
import eGR8Conf from 'events/2014-July-United States-MN-Minneapolis-GR8Conf.json';
import eGraceHopperspaceCelebrationspaceofspaceWomenspaceinspaceComputing from 'events/2015-October-United States-TX-Houston-Grace Hopper Celebration of Women in Computing.json';
import eGraphLab from 'events/2014-July-United States-CA-San Francisco-Graph Lab.json';
import eGreach2014 from 'events/2015-April-Spain-unknown-stateProvince-Madrid-Greach 2014.json';
import eGreHack from 'events/unknown-start-France-unknown-stateProvince-Grenoble-GreHack.json';
import eGrrCON from 'events/unknown-start-United States-MI-Grand Rapids-GrrCON.json';
import eGWTdotcreate from 'events/2015-January-United States-CA-Mountain View-GWT.create.json';
import eHackinspaceParis from 'events/unknown-start-France-unknown-stateProvince-Paris-Hack in Paris.json';
import eHackinspacethespacebox from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-Hack in the box.json';
import eHackdotlu from 'events/unknown-start-Luxemburg-unknown-stateProvince-Luxemburg-Hack.lu.json';
import eHackference from 'events/2015-October-United Kingdom-unknown-stateProvince-Birmingham-Hackference.json';
import eHackfest from 'events/unknown-start-Canada-QC-Montreal-Hackfest.json';
import eHacktivity from 'events/unknown-start-Hungary-unknown-stateProvince-Budapest-Hacktivity.json';
import eHadoopSummit from 'events/2015-June-United States-CA-San Jose-Hadoop Summit.json';
import eHadoopWorld from 'events/2015-September-United States-NY-New York-Hadoop World.json';
import eHalfStack from 'events/2017-November-United Kingdom-unknown-stateProvince-London-HalfStack.json';
import eHardweardotio from 'events/unknown-start-The Netherlands-unknown-stateProvince-The Hague-Hardwear.io.json';
import eHaskellSymposium from 'events/unknown-start-Canada-BC-Vancouver-Haskell Symposium.json';
import eHeartlandDevspaceConference from 'events/unknown-start-United States-NE-Omaha-Heartland Dev Conference.json';
import eHighEdWeb from 'events/unknown-start-United States-WI-Milwaukee-HighEd Web.json';
import eHolyJS from 'events/unknown-start-Russia-unknown-stateProvince-St. Petersburg-HolyJS.json';
import eHolyJSMoscow from 'events/unknown-start-Russia-unknown-stateProvince-Moscow-HolyJS Moscow.json';
import eHowInteractivespaceDesign from 'events/unknown-start-United States-IL-Chicago-How Interactive Design.json';
import eHTML5DevspaceConf from 'events/unknown-start-United States-CA-San Francisco-HTML5 Dev Conf.json';
import eHTML5DevConf from 'events/2015-October-United States-CA-San Francisco-HTML5DevConf.json';
import eHybridConf from 'events/2015-August-Ireland-unknown-stateProvince-Dublin-HybridConf.json';
import eILovespaceAPIs from 'events/2015-October-United States-CA-San Jose-I Love APIs.json';
import eIBMEnterprise2014 from 'events/2014-October-United States-NV-Las Vegas-IBM Enterprise2014.json';
import eIEEESandP from 'events/unknown-start-United States-CA-San Jose-IEEE S&P.json';
import eiJSInternationalspaceJavaScriptspaceConference from 'events/unknown-start-Germany-unknown-stateProvince-Munich-iJS International JavaScript Conference.json';
import eInsomnisquotehack from 'events/unknown-start-Switzerland-unknown-stateProvince-Geneva-Insomni'hack.json';
import eINSTINT from 'events/2015-September-United States-MN-Minneapolis-INST-INT.json';
import eIntelIDF14 from 'events/2014-September-United States-CA-San Francisco-Intel IDF14.json';
import eInterConAndroid from 'events/2014-September-Brazil-unknown-stateProvince-Sao Paulo-InterCon Android.json';
import eInternetofspaceThingsspaceForumspace2014 from 'events/2015-March-United Kingdom-unknown-stateProvince-Cambridge-Internet of Things Forum 2014.json';
import eiOSCon2017 from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-iOSCon 2017.json';
import eiOSDCJapanspace2017 from 'events/unknown-start-Japan-unknown-stateProvince-Tokyo-iOSDC Japan 2017.json';
import eiOSDevUk from 'events/unknown-start-United Kingdom-Wales-Aberystwyth-iOSDevUk.json';
import eIoTSecurityspaceSummit from 'events/unknown-start-Canada-BC-Vancouver-IoT Security Summit.json';
import eIoTWorldspaceForum from 'events/2015-November-United Kingdom-unknown-stateProvince-London-IoT World Forum.json';
import eIowaCodespaceCamp from 'events/2017-November-United States-IA-Des Moines-Iowa Code Camp.json';
import eItcampspaceRomania from 'events/unknown-start-Romania-unknown-stateProvince-unknown-city-It camp Romania.json';
import eITWeekend from 'events/unknown-start-Ukraine-unknown-stateProvince-Dnipropetrovsk-IT Weekend.json';
import eITfwslashDevConnections from 'events/2014-September-United States-NV-Las Vegas-ITDev Connections.json';
import eJavaLand from 'events/2016-March-Germany-unknown-stateProvince-Bruhl-JavaLand.json';
import eJavaOne from 'events/2015-October-United States-CA-San Francisco-JavaOne.json';
import eJavaScriptConference from 'events/unknown-start-United States-TX-Austin-JavaScript Conference.json';
import eJavascriptDay from 'events/2015-October-Italy-unknown-stateProvince-Verona-Javascript Day.json';
import eJavaZone from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-JavaZone.json';
import eJazoon from 'events/unknown-start-Switzerland-unknown-stateProvince-Bern-Jazoon.json';
import eJazzCondotTech from 'events/2018-March-United States-LA-New Orleans-JazzCon.Tech.json';
import eJFall from 'events/2014-November-Holland-unknown-stateProvince-Nijkerk-JFall.json';
import eJfokus from 'events/2015-February-Sweden-unknown-stateProvince-Stockholm-Jfokus.json';
import eJoyofspaceCoding from 'events/unknown-start-The Netherlands-unknown-stateProvince-Rotterdam-Joy of Coding.json';
import ejQueryConf from 'events/unknown-start-Russia-unknown-stateProvince-Moscow-jQuery Conf.json';
import ejQueryConf from 'events/unknown-start-United States-IL-Chicago-jQuery Conf.json';
import ejQueryConference from 'events/2015-June-United States-CA-San Francisco-jQuery Conference.json';
import ejQueryDevspaceSummit from 'events/unknown-start-United States-NY-New York-jQuery Dev Summit.json';
import eJQueryUK from 'events/2015-March-United Kingdom-unknown-stateProvince-Oxford-JQuery UK.json';
import ejQueryConf from 'events/unknown-start-United States-CA-San Francisco-jQueryConf.json';
import eJSDay from 'events/2018-May-Italy-unknown-stateProvince-Verona-JS Day.json';
import eJSfwdays from 'events/unknown-start-Ukraine-unknown-stateProvince-Kyiv-JS fwdays.json';
import eJSHeroes from 'events/unknown-start-Romania-unknown-stateProvince-Cluj-Napoca-JS Heroes.json';
import eJSKongress from 'events/unknown-start-Germany-unknown-stateProvince-Munich-JS Kongress.json';
import eJSPoland from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-JS Poland.json';
import eJSRemotespaceConf from 'events/unknown-start-unknown-country-unknown-stateProvince-Online-JS Remote Conf.json';
import eJSChannel from 'events/unknown-start-India-unknown-stateProvince-Bengaluru-JSChannel.json';
import eJSConf from 'events/2014-September-Germany-unknown-stateProvince-Berlin-JSConf.json';
import eJSConfBudapest from 'events/unknown-start-Hungary-unknown-stateProvince-Budapest-JSConf Budapest.json';
import eJSConfChina from 'events/unknown-start-China-unknown-stateProvince-Shanghai-JSConf China.json';
import eJSConfColombia from 'events/unknown-start-Colombia-unknown-stateProvince-Medellin-JSConf Colombia.json';
import eJSConfEU from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-JSConf EU.json';
import eJSConfUS from 'events/unknown-start-United States-FL-Amelia Island-JSConf US.json';
import ejsconfdotbe from 'events/unknown-start-Belgium-unknown-stateProvince-Brugg-jsconf.be.json';
import eJSConfAsia from 'events/unknown-start-Singapore-unknown-stateProvince-Singapore-JSConfAsia.json';
import eJSConfAU from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-JSConfAU.json';
import eJSCONFCo from 'events/unknown-start-Colombia-unknown-stateProvince-Medellin-JSCONFCo.json';
import eJSConfUY from 'events/unknown-start-Uruguay-unknown-stateProvince-Montevideo-JSConfUY.json';
import eJSDayItaly from 'events/unknown-start-Italy-unknown-stateProvince-Verona-JSDay Italy.json';
import eJSDC from 'events/2014-October-Taiwan-unknown-stateProvince-Taipei City-JSDC.json';
import eJSFest from 'events/2014-March-United States-CA-San Francisco-JSFest.json';
import ejsfoo from 'events/unknown-start-India-unknown-stateProvince-Bangalore-jsfoo.json';
import eJSFooIndia from 'events/2015-September-India-unknown-stateProvince-Bangalore-JSFoo India.json';
import eJSinSA from 'events/unknown-start-South Africa-unknown-stateProvince-Johannesburg-JSinSA.json';
import ejsist from 'events/2014-September-Turkey-unknown-stateProvince-Instabul-jsist.json';
import eJSUnconf from 'events/unknown-start-Germany-unknown-stateProvince-Hamburg-JSUnconf.json';
import eKalamazooX from 'events/unknown-start-United States-MI-Kalamazoo-KalamazooX.json';
import eKCDC from 'events/2015-June-United States-MO-Kansas City-KCDC.json';
import eKiwicon from 'events/unknown-start-New Zealand-unknown-stateProvince-Wellington-Kiwicon.json';
import eKiwiParty from 'events/unknown-start-France-unknown-stateProvince-Strasbourg-KiwiParty.json';
import eLanuitspaceduspacehack from 'events/unknown-start-France-unknown-stateProvince-Paris-La nuit du hack.json';
import eLARubyConf from 'events/unknown-start-United States-CA-Long Beach-LA RubyConf.json';
import eLambdaWorld from 'events/unknown-start-Spain-unknown-stateProvince-Cadiz-Lambda World.json';
import eLatinoware from 'events/2015-October-Brazil-unknown-stateProvince-Foz do Iguaçu-Latinoware.json';
import eLCA from 'events/unknown-start-New Zealand-unknown-stateProvince-Auckland-LCA.json';
import eLeanDayspaceLondonspaceparensLSOspaceShoreditchparens from 'events/2014-March-United Kingdom-unknown-stateProvince-London-Lean Day London (LSO Shoreditch).json';
import eLeanStartupspaceConference from 'events/2015-November-United States-CA-San Francisco-Lean Startup Conference.json';
import eLesbiansWhospaceTech from 'events/unknown-start-United States-NY-New York-Lesbians Who Tech.json';
import eLeWeb from 'events/2014-December-France-unknown-stateProvince-Paris-LeWeb.json';
import eLibertyJS from 'events/unknown-start-United States-PA-Philadelphia-LibertyJS.json';
import eLinuxTag from 'events/2015-August-Germany-unknown-stateProvince-Berlin-LinuxTag.json';
import eLISAConference from 'events/2014-November-United States-WA-Seattle-LISA Conference.json';
import eLoneStarspacePHP from 'events/2015-April-United States-TX-Dallas-Lone Star PHP.json';
import eLuceneRevolution from 'events/unknown-start-Ireland-unknown-stateProvince-Dublin-Lucene Revolution.json';
import eMAwomensquotesspaceconference from 'events/unknown-start-United States-MA-Boston-MA women's conference.json';
import eMacAdminspaceandspaceDeveloperspaceConferencespaceUK from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Mac Admin & Developer Conference UK.json';
import eMacAdmins from 'events/unknown-start-United States-PA-State College-MacAdmins.json';
import eMacworld from 'events/2014-March-United States-CA-San Francisco-Macworld.json';
import eMadisonPHP from 'events/2017-September-United States-WI-Madison-Madison PHP.json';
import eMadison+Ruby from 'events/2015-April-United States-WI-Madison-Madison+ Ruby.json';
import eMagentoImagine from 'events/2016-April-United States-NV-Las Vegas-Magento Imagine.json';
import eMagmaConf from 'events/2015-June-Mexico-unknown-stateProvince-Manzanillo-MagmaConf.json';
import eMakerFairespaceNewcastle from 'events/2015-April-United Kingdom-unknown-stateProvince-Newcastle-Maker Faire Newcastle.json';
import eMakingWeb from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-MakingWeb.json';
import eMALWARE from 'events/unknown-start-United States-PR-Puerto Rico-MALWARE.json';
import eManhattanJS from 'events/2015-September-United States-NY-New York-ManhattanJS.json';
import eMCE from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-MCE.json';
import eMedellinJS from 'events/2015-September-Colombia-unknown-stateProvince-Madellin-Medellin JS.json';
import emediaconventionparenspartspaceofspacerecolonpublicaparens from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-mediaconvention (part of republica).json';
import eMicrosoftIgnite from 'events/unknown-start-United States-FL-Orlando-Microsoft Ignite.json';
import eMicrosoftMVPspaceSummit from 'events/unknown-start-United States-WA-Redmond-Microsoft MVP Summit.json';
import eMidwestGamespaceDevspaceExpo from 'events/2017-September-United States-OH-Columbus-Midwest Game Dev Expo.json';
import eMidwestJS from 'events/unknown-start-United States-MN-Minneapolis-Midwest JS.json';
import eMidwestPHP from 'events/unknown-start-United States-MN-Minneapolis-Midwest PHP.json';
import eMidwestTechspaceFest from 'events/unknown-start-United States-OH-Columbus-Midwest Tech Fest.json';
import eMidwestdotio from 'events/unknown-start-United States-MO-Kansas City-Midwest.io.json';
import eMidwestJS from 'events/2015-August-United States-MN-Minneapolis-MidwestJS.json';
import eMidwestUX from 'events/unknown-start-United States-PA-Pittsburgh-MidwestUX.json';
import eMilwaukeeCodespaceCamp from 'events/2017-October-United States-WI-Milwaukee-Milwaukee Code Camp.json';
import eMinnesotaDevelopersspaceConference from 'events/2017-October-United States-MN-Minneapolis-Minnesota Developers Conference.json';
import eMirrorConfspace2017 from 'events/unknown-start-Portugal-unknown-stateProvince-Braga-Mirror Conf 2017.json';
import eMobileDevspaceSummit from 'events/unknown-start-India-unknown-stateProvince-Bangalore-Mobile Dev Summit.json';
import eMobileEra from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-Mobile Era.json';
import eMobileWebDevConf from 'events/unknown-start-United States-CA-San Francisco-MobileWebDevConf.json';
import eModernWebspaceConf from 'events/2014-August-unknown-country-unknown-stateProvince-unknown-city-Modern Web Conf.json';
import eMonashUniversity from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-Monash University.json';
import eMonitorama from 'events/2015-June-United States-OR-Portland-Monitorama.json';
import eMonktoberfest from 'events/2015-October-United States-ME-Portland-Monktoberfest.json';
import eMoonshotCon from 'events/2015-January-United States-UT-Park City-MoonshotCon.json';
import eMoscowJS from 'events/2014-April-Russia-unknown-stateProvince-Moscow-MoscowJS.json';
import eMountainWestJavaScript from 'events/2015-March-United States-UT-Salt Lake City-MountainWest JavaScript.json';
import eMozFest from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-MozFest.json';
import eMtnWestJS2015 from 'events/unknown-start-United States-UT-Salt Lake City-MtnWestJS 2015.json';
import eMusicCityspaceCode from 'events/unknown-start-United States-TN-Nashville-Music City Code.json';
import eNAB from 'events/unknown-start-United States-NV-Las Vegas-NAB.json';
import eNationJS from 'events/2017-December-United States-DC-Washington-NationJS.json';
import eNCDevCon from 'events/unknown-start-United States-NC-Raleigh-NCDevCon.json';
import eNDC from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-NDC.json';
import eNDCLondon from 'events/2018-January-United Kingdom-unknown-stateProvince-London-NDC London.json';
import eNDCOslo from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-NDC Oslo.json';
import eNDCSydney from 'events/unknown-start-Australia-unknown-stateProvince-Sydney-NDC Sydney.json';
import eNDSS from 'events/unknown-start-United States-CA-San Diego-NDSS.json';
import eNebraskadotCodeparensparens from 'events/unknown-start-United States-NE-Lincoln-Nebraska.Code().json';
import eNebraskaJS from 'events/unknown-start-United States-NE-Omaha-NebraskaJS.json';
import eNEJSCONF from 'events/unknown-start-United States-NE-Omaha-NEJS CONF.json';
import eNetConfdotUY from 'events/unknown-start-Uruguay-unknown-stateProvince-Montevideo-NetConf.UY.json';
import eNetSecureDay from 'events/unknown-start-France-unknown-stateProvince-Rouen-NetSecure Day.json';
import eNewDirectionsspaceinspaceOperatingspaceSystems from 'events/2014-November-United Kingdom-unknown-stateProvince-London-New Directions in Operating Systems.json';
import eNewYorkspaceCityspaceCodespaceCamp from 'events/2017-October-USA-NY-New York-New York City Code Camp.json';
import eNGEuropespaceparensAngularJSparens from 'events/2014-October-France-unknown-stateProvince-Paris-NG Europe (AngularJS).json';
import eNGBE from 'events/unknown-start-Belgium-unknown-stateProvince-Ghent-NG-BE.json';
import eNGConf from 'events/2018-April-United States-UT-Salt Lake City-NG-Conf.json';
import eNGNL from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-NG-NL.json';
import engAtlanta from 'events/2001-January-USA-Georgia-Atlanta-ngAtlanta.json';
import enginxdotconf from 'events/2015-September-United States-CA-San Francisco-nginx.conf.json';
import engPoland from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-ngPoland.json';
import engVikings from 'events/unknown-start-Denmark-unknown-stateProvince-Copenhagen-ngVikings.json';
import eNodeInteractive from 'events/unknown-start-Canada-BC-Vancouver-Node Interactive.json';
import eNodedotjsInteractivespaceNorthspaceAmerica from 'events/2017-October-Canada-British Columbia-Vancouver-Node.js Interactive North America.json';
import enodeconf from 'events/2015-June-United States-CA-Walter Creek Ranch-nodeconf.json';
import eNodeConfArgentina from 'events/unknown-start-Argentina-unknown-stateProvince-Buenos Aires-NodeConf Argentina.json';
import eNodeConfBarcelona from 'events/unknown-start-Spain-unknown-stateProvince-Barcelona-NodeConf Barcelona.json';
import eNodeConfEurope from 'events/2015-September-Ireland-unknown-stateProvince-Waterford-NodeConf Europe.json';
import eNodeConfEU from 'events/unknown-start-Ireland-unknown-stateProvince-Kilkenny-NodeConfEU.json';
import eNodeSummit from 'events/unknown-start-United States-CA-San Francisco-NodeSummit.json';
import eNodevember from 'events/unknown-start-United States-TN-Nashville-Nodevember.json';
import eNodevember from 'events/2017-November-United States-TN-Nashville-Nodevember.json';
import eNOPCon from 'events/unknown-start-Turkey-unknown-stateProvince-Instabul-NOPCon.json';
import eNordicJS from 'events/2015-September-Sweden-unknown-stateProvince-Artipelag-NordicJS.json';
import eNorthBayspacePython from 'events/2017-December-United States-CA-Petaluma-North Bay Python.json';
import eNoSQLNow from 'events/unknown-start-United States-CA-San Jose-NoSQL Now.json';
import eNotFluffJustStuff from 'events/unknown-start-unknown-country-unknown-stateProvince-various-NotFluffJustStuff.json';
import eNullCon from 'events/unknown-start-India-unknown-stateProvince-Goa-NullCon.json';
import eNYCCodespaceCamp from 'events/unknown-start-United States-NY-New York-NYC Code Camp.json';
import eNYCCamp from 'events/unknown-start-United States-NY-New York-NYCCamp.json';
import eOsquoteReillyarchspaceconf from 'events/unknown-start-unknown-country-unknown-stateProvince-various-O'Reilly arch conf.json';
import eOsquoteReillyFluent from 'events/unknown-start-United States-CA-San Jose-O'Reilly Fluent.json';
import eOsquoteReillyOSCONspaceAustin from 'events/unknown-start-United States-TX-Austin-O'Reilly OSCON Austin.json';
import eOaklandJS from 'events/unknown-start-United States-CA-Oakland-OaklandJS.json';
import eOculusConnect from 'events/2015-September-United States-CA-Los Angeles-Oculus Connect.json';
import eOdessaJS from 'events/unknown-start-Ukraine-unknown-stateProvince-Odessa-OdessaJS.json';
import eOggCamp from 'events/2015-October-United Kingdom-unknown-stateProvince-Oxford-OggCamp.json';
import eOhioLinuxFest from 'events/2017-September-United States-OH-Columbus-Ohio LinuxFest.json';
import eOOP from 'events/2016-February-Germany-unknown-stateProvince-Munich-OOP.json';
import eOpenSourcespaceandspaceFeelings from 'events/unknown-start-United States-WA-Seattle-Open Source & Feelings.json';
import eOpenWebspaceCamp from 'events/2015-August-United States-CA-San Jose-Open Web Camp.json';
import eOpenCon from 'events/2014-September-United States-SC-Charlseton-OpenCon.json';
import eOpenFest from 'events/2014-November-Bulgaria-unknown-stateProvince-Sofia-OpenFest.json';
import eOpenStackSummit from 'events/2015-October-Japan-unknown-stateProvince-Tokyo-OpenStack Summit.json';
import eOpenVisConf from 'events/2015-April-United States-MA-Boston-OpenVis Conf.json';
import eOpenWest from 'events/2015-May-United States-UT-Orem-OpenWest.json';
import eOracleOpenspaceWorld from 'events/2014-September-United States-CA-San Francisco-Oracle Open World.json';
import eOSBridge from 'events/2015-June-United States-OR-Portland-OS Bridge.json';
import eOSCon from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-OSCon.json';
import eOSCON from 'events/2015-July-United States-OR-Portland-OSCON.json';
import eOSDC from 'events/2015-October-Australia-unknown-stateProvince-Gold Coast-OSDC.json';
import eParanoia from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-Paranoia.json';
import eParisWeb from 'events/unknown-start-France-unknown-stateProvince-Paris-Paris Web.json';
import ePechaKucha from 'events/unknown-start-Canada-unknown-stateProvince-Ottawa-Pecha Kucha.json';
import ePhDays from 'events/unknown-start-Russia-unknown-stateProvince-Moscow-PhDays.json';
import ephpConferencespaceArgentina from 'events/2014-November-Argentina-unknown-stateProvince-Buenos Aires-php Conference Argentina.json';
import ePHPCraft from 'events/unknown-start-South Africa-unknown-stateProvince-Johannesburg-PHP Craft.json';
import ePHPDay from 'events/2015-May-Italy-unknown-stateProvince-Verona-PHP Day.json';
import ePHPBenelux from 'events/unknown-start-Belgium-unknown-stateProvince-Antwerp-PHPBenelux.json';
import ePHPNWManchester from 'events/2014-October-United Kingdom-unknown-stateProvince-UK-PHPNW Manchester.json';
import ePHPUK from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-PHPUK.json';
import ePinkElephant from 'events/unknown-start-United States-NV-Las Vegas-Pink Elephant.json';
import ePipelineConf from 'events/2015-March-United Kingdom-unknown-stateProvince-London-PipelineConf.json';
import epitercss from 'events/unknown-start-Russia-unknown-stateProvince-St. Petersburg-pitercss.json';
import ePlaygrounds from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-Playgrounds.json';
import ePLIBMTTBHGATY from 'events/2017-October-US-IA-Des Moines-PLIBMTTBHGATY.json';
import ePluralsightAuthorspaceSummit from 'events/unknown-start-United States-UT-Salt Lake City-Pluralsight Author Summit.json';
import ePNWScala from 'events/2014-November-United States-OR-Portland-PNWScala.json';
import ePolyConf from 'events/2015-July-Poland-unknown-stateProvince-Poznan-PolyConf.json';
import ePolyconf2014 from 'events/unknown-start-Poland-unknown-stateProvince-Poznan-Polyconf 2014.json';
import ePostgresConference from 'events/2015-June-Canada-ON-Ottawa-Postgres Conference.json';
import ePostgresOpen from 'events/unknown-start-United States-TX-Dallas-PostgresOpen.json';
import ePragmaConference from 'events/2015-October-Italy-unknown-stateProvince-florence-Pragma Conference.json';
import ePrairieCode from 'events/unknown-start-United States-IA-Des Moines-Prairie Code.json';
import ePrairieDevspaceCon from 'events/unknown-start-Canada-unknown-stateProvince-Winnipeg-Prairie Dev Con.json';
import ePrairiedotCodeparensparens from 'events/2017-September-United States-IA-Des Moines-Prairie.Code().json';
import ePressnomics from 'events/unknown-start-United States-AZ-Phoenix-Pressnomics.json';
import ePuppetConf from 'events/2015-October-United States-CA-San Francisco-PuppetConf.json';
import ePuppetconf from 'events/unknown-start-United States-OR-Portland-Puppetconf.json';
import ePyCon from 'events/2015-April-Canada-QC-Montreal-PyCon.json';
import ePyConArgentina from 'events/2014-November-Argentina-unknown-stateProvince-Rafaela-PyCon Argentina.json';
import ePyConAU from 'events/2015-July-Australia-unknown-stateProvince-Brisbane-PyCon AU.json';
import ePyConFI from 'events/unknown-start-Finland-unknown-stateProvince-Helsinki-PyCon FI.json';
import ePyconFR from 'events/unknown-start-France-unknown-stateProvince-Pau-Pycon FR.json';
import ePyConIreland from 'events/2014-October-Ireland-unknown-stateProvince-Dublin-PyCon Ireland.json';
import ePyconPL from 'events/2015-October-Poland-unknown-stateProvince-Szczyrk-Pycon PL.json';
import ePyconUK from 'events/2015-September-United Kingdom-unknown-stateProvince-Coventry-Pycon UK.json';
import ePyConUruguay from 'events/2013-November-Uruguay-unknown-stateProvince-Montevideo-PyCon Uruguay.json';
import ePyData from 'events/2015-September-United States-NY-New York-PyData.json';
import ePyGotham from 'events/2014-August-United States-NY-New York-PyGotham.json';
import ePyOhio from 'events/2015-August-United States-OH-Columbus-PyOhio.json';
import ePyTennessee from 'events/2015-February-United States-TN-Nashville-PyTennessee.json';
import ePyTexas from 'events/2015-September-United States-TX-College Station-PyTexas.json';
import eQcon from 'events/unknown-start-Brazil-unknown-stateProvince-Sao Paulo-Qcon.json';
import eQcon from 'events/unknown-start-China-unknown-stateProvince-Beijing-Qcon.json';
import eQcon from 'events/unknown-start-China-unknown-stateProvince-Shanghai-Qcon.json';
import eQcon from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Qcon.json';
import eQCon from 'events/2015-November-United States-CA-San Francisco-QCon.json';
import eQcon from 'events/unknown-start-United States-CA-San Francisco-Qcon.json';
import eQcon from 'events/unknown-start-United States-NY-New York-Qcon.json';
import er2con from 'events/unknown-start-Spain-unknown-stateProvince-Barcelona-r2con.json';
import eRailsConf from 'events/2015-April-United States-GA-Atlanta-RailsConf.json';
import eRailsconf from 'events/unknown-start-United States-GA-Atlanta-Railsconf.json';
import eRailsconf from 'events/unknown-start-United States-OR-Portland-Railsconf.json';
import eRailsGirlsAmsterdam from 'events/2012-May-The Netherlands-unknown-stateProvince-Amsterdam-RailsGirls Amsterdam.json';
import eRedotWorkInternetspaceofspaceThings from 'events/2015-March-United Kingdom-unknown-stateProvince-London-Re.Work Internet of Things.json';
import erecolonpublica from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-republica.json';
import eReactparensShoreditchspaceWorksspaceVillagespaceHallparens from 'events/2014-April-United Kingdom-unknown-stateProvince-London-React (Shoreditch Works Village Hall).json';
import eReactAlicante from 'events/unknown-start-Spain-unknown-stateProvince-Alicante-React Alicante.json';
import eReactAmsterdam from 'events/2018-April-The Netherlands-unknown-stateProvince-Amsterdam-React Amsterdam.json';
import eReactBoston from 'events/2017-September-United States-MA-Boston-React Boston.json';
import eReactConf from 'events/unknown-start-United States-CA-Santa Clara-React Conf.json';
import eReactConfspaceBrasil from 'events/unknown-start-Brazil-unknown-stateProvince-Sao Paulo-React Conf Brasil.json';
import eReactDayspace2017 from 'events/unknown-start-Italy-unknown-stateProvince-Verona-React Day 2017.json';
import eReactDayspaceBerlin from 'events/2017-December-Germany-unknown-stateProvince-Berlin-React Day Berlin.json';
import eReactEurope from 'events/unknown-start-France-unknown-stateProvince-Paris-React Europe.json';
import eReactLondon from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-React London.json';
import eReactNativespaceEU from 'events/unknown-start-Poland-unknown-stateProvince-Wrocław-React Native EU.json';
import eReactRally from 'events/unknown-start-USA-Louisiana-Salt Lake City-React Rally.json';
import eReactConfEU from 'events/unknown-start-France-unknown-stateProvince-Paris-ReactConf EU.json';
import eReactEurope from 'events/unknown-start-France-unknown-stateProvince-Paris-ReactEurope.json';
import eReactFoo from 'events/unknown-start-India-unknown-stateProvince-Bangalore-ReactFoo.json';
import eReactiveConf from 'events/2017-October-Slovakia-unknown-stateProvince-Bratislava-Reactive Conf.json';
import eReactiveConf from 'events/unknown-start-United States-TX-Austin-ReactiveConf.json';
import eReactJSDay from 'events/unknown-start-Italy-unknown-stateProvince-Verona-ReactJSDay.json';
import eReactNext from 'events/unknown-start-Israel-unknown-stateProvince-Tel Aviv-ReactNext.json';
import eReactRally from 'events/unknown-start-United States-UT-Salt Lake City-ReactRally.json';
import eRealtimeConfEU from 'events/2013-April-France-unknown-stateProvince-Lyon-RealtimeConf EU.json';
import eRecon from 'events/unknown-start-Canada-QC-Montreal-Recon.json';
import eRecurseCenter from 'events/unknown-start-United States-NY-New York-Recurse Center.json';
import eRedDotRubyConf from 'events/unknown-start-Singapore-unknown-stateProvince-Singapore-RedDotRubyConf.json';
import eRefresh from 'events/unknown-start-Estonia-unknown-stateProvince-Tallinn-Refresh.json';
import eRefreshOttawa from 'events/unknown-start-Canada-unknown-stateProvince-Ottawa-Refresh Ottawa.json';
import eRejectdotjs from 'events/2015-September-Germany-unknown-stateProvince-Berlin-Reject.js.json';
import eRender from 'events/2018-March-England-unknown-stateProvince-Oxford-Render.json';
import eRESTFEST from 'events/2015-September-United States-SC-Greenville-REST FEST.json';
import eRevolutionConf from 'events/unknown-start-United States-VA-Virginia Beach-RevolutionConf.json';
import eRigaDevspaceDays from 'events/unknown-start-unknown-country-unknown-stateProvince-Riga-Riga Dev Days.json';
import eRMLLSecurityspacetrack from 'events/unknown-start-France-unknown-stateProvince-Saint Etienne-RMLL Security track.json';
import eRobotsConf from 'events/2014-December-United States-FL-Amelia Island-RobotsConf.json';
import eRootedCon from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-RootedCon.json';
import eRSAconference from 'events/unknown-start-United States-CA-San Francisco-RSA conference.json';
import eRubyConf from 'events/2015-November-United States-TX-San Antonio-RubyConf.json';
import eRubyConfArgentina from 'events/2014-October-Argentina-unknown-stateProvince-Buenos Aires-RubyConf Argentina.json';
import eRubyConfAU from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-RubyConf AU.json';
import eRubyConfBrasil from 'events/2015-September-Brazil-unknown-stateProvince-Sao Paulo-RubyConf Brasil.json';
import eRubyConfColombia from 'events/unknown-start-Colombia-unknown-stateProvince-Medellin-RubyConf Colombia.json';
import eRubyConfUruguay from 'events/2014-May-Uruguay-unknown-stateProvince-Montevideo-RubyConf Uruguay.json';
import eRubyslava from 'events/2015-June-Slovakia-unknown-stateProvince-Bratislava-Rubyslava.json';
import eRuhrJS from 'events/unknown-start-Germany-unknown-stateProvince-Bochum-RuhrJS.json';
import eRuhrSec from 'events/unknown-start-Germany-unknown-stateProvince-Bochum-RuhrSec.json';
import eRuLu from 'events/unknown-start-France-unknown-stateProvince-Lyon-RuLu.json';
import eRuxcon from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-Ruxcon.json';
import eRVAJavaScript from 'events/2017-November-United States-VA-Richmond-RVA JavaScript.json';
import eRWDevCon from 'events/2016-March-United States-VA-Alexandria-RWDevCon.json';
import eSaltConf17 from 'events/2017-October-USA-UT-Salt Lake City-SaltConf17.json';
import eSaminaireAccessiweb from 'events/unknown-start-France-unknown-stateProvince-Paris-Saminaire Accessiweb.json';
import eSamsungDeveloper from 'events/2016-March-United States-CA-San Francisco-Samsung Developer.json';
import eSAS from 'events/unknown-start-St. Maarten-unknown-stateProvince-St Maarten-SAS.json';
import eSaSeIoT from 'events/unknown-start-Spain-unknown-stateProvince-Valencia-SaSeIoT.json';
import eSassConf from 'events/2015-November-United States-TX-Austin-SassConf.json';
import eScalaByspaceThespaceBay from 'events/2015-August-United States-CA-San Francisco-Scala By The Bay.json';
import eScalaDays from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-Scala Days.json';
import eScalaIO from 'events/2015-October-France-unknown-stateProvince-Paris-Scala IO.json';
import eScalaUnderscore from 'events/unknown-start-Israel-unknown-stateProvince-Tel Aviv-Scala Underscore.json';
import eSCALE16xspacespace16thspaceAnnualspaceSouthernspaceCaliforniaspaceLinuxspaceExpo from 'events/2018-March-United States-CA-Pasadena-SCALE 16x - 16th Annual Southern California Linux Expo.json';
import eScotlandjs from 'events/unknown-start-Scotland-unknown-stateProvince-Edinburgh-Scotlandjs.json';
import eScottishRubyspaceConf from 'events/2014-May-Scotland-unknown-stateProvince-Perthshire-Scottish Ruby Conf.json';
import eScript from 'events/unknown-start-Austria-unknown-stateProvince-Linz-Script.json';
import eSeaGL from 'events/2017-October-United States-WA-Seattle-SeaGL.json';
import eSeattleJS from 'events/unknown-start-United States-WA-Seattle-SeattleJS.json';
import eSecT from 'events/unknown-start-Sweden-unknown-stateProvince-Stockholm-Sec-T.json';
import eSecITC from 'events/unknown-start-Romania-unknown-stateProvince-Bucharest-SecITC.json';
import eSecTor from 'events/unknown-start-Canada-ON-Toronto-SecTor.json';
import eSecuriTay from 'events/unknown-start-Scotland-unknown-stateProvince-Dundee-SecuriTay.json';
import eSecurityofspaceThingsspaceWorld from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-Security of Things World.json';
import eSFPCSalon from 'events/unknown-start-United States-NY-New York-SFPC Salon.json';
import eSHA2017 from 'events/unknown-start-The Netherlands-unknown-stateProvince-Scoutinglandgoed in Zeewolde-SHA2017.json';
import eSharePointFestspaceChicago from 'events/2017-December-United States-IL-Chicago-SharePoint Fest Chicago.json';
import eSharkFestsquote17spaceEurope from 'events/2017-November-Portugal-unknown-stateProvince-Estoril-SharkFest '17 Europe.json';
import eShe’sGeeky from 'events/2015-September-United States-UT-Salt Lake City-She’s Geeky.json';
import eShmooCon from 'events/unknown-start-United States-DC-Washington-ShmooCon.json';
import eSiliconValleyspaceCodespaceCamp from 'events/unknown-start-United States-CA-San Jose-Silicon Valley Code Camp.json';
import eSIMBig from 'events/2014-September-Peru-unknown-stateProvince-Cusco-SIMBig.json';
import eSmallisspaceBeautiful from 'events/unknown-start-Scotland-unknown-stateProvince-Glasgow-Small is Beautiful.json';
import eSmartTravel from 'events/unknown-start-Portugal-unknown-stateProvince-Lisbon-Smart Travel.json';
import eSmashingConfSanspaceFrancisco from 'events/unknown-start-United States-CA-San Francisco-SmashingConf San Francisco.json';
import eSmidig from 'events/unknown-start-Norway-unknown-stateProvince-Oslo-Smidig.json';
import eSoEmber from 'events/unknown-start-United States-CA-San Diego-So Ember.json';
import eSocialConnections from 'events/unknown-start-Czech Republic-unknown-stateProvince-Prague-Social Connections.json';
import eSoftwareArchitecture from 'events/2015-March-United States-MA-Boston-Software Architecture.json';
import eSoftwareDesignspaceandspaceDevspaceparensSDDparens from 'events/2015-May-United Kingdom-unknown-stateProvince-London-Software Design & Dev (SDD).json';
import eSolid from 'events/2014-May-United States-CA-San Francisco-Solid.json';
import eSourceUpbang from 'events/unknown-start-South Africa-unknown-stateProvince-Johannesburg-Source Up!.json';
import eSouthEastLinuxFest from 'events/2014-June-United States-NC-Charlotte-SouthEast LinuxFest.json';
import eSoutheastRuby from 'events/2017-October-United States-TN-Nashville-Southeast Ruby.json';
import eSpaceCityspaceJS from 'events/2015-March-United States-TX-Houston-Space City JS.json';
import eSplunkdotconf2014 from 'events/2015-September-United States-NV-Las Vegas-Splunk .conf2014.json';
import eSpringOne2GX from 'events/unknown-start-United States-WA-Seattle-SpringOne 2GX.json';
import eSRCCON from 'events/2015-June-United States-PA-Minneapolis-SRCCON.json';
import eSSTIC from 'events/unknown-start-France-unknown-stateProvince-Rennes-SSTIC.json';
import eStarsConf2017 from 'events/2017-November-Chile--Santiago-StarsConf 2017.json';
import eStartupGrind from 'events/2016-February-United States-CA-Redwood City-Startup Grind.json';
import eStateofspacethespaceMapspaceUS from 'events/2017-October-US-CO-Boulder-State of the Map US.json';
import eSteelCon from 'events/unknown-start-United Kingdom-unknown-stateProvince-Sheffield-SteelCon.json';
import eStirTrek from 'events/unknown-start-United States-OH-Columbus-Stir Trek.json';
import eStpcon from 'events/unknown-start-United States-MA-Boston-Stpcon.json';
import eStrangeloop from 'events/2017-September-United States-MO-St. Louis-Strangeloop.json';
import eStrataConf from 'events/2018-May-United Kingdom-unknown-stateProvince-London-Strata Conf.json';
import eStrataConf from 'events/2017-September-United States-NY-New York-Strata Conf.json';
import eSudWeb from 'events/unknown-start-France-unknown-stateProvince-Toulouse-Sud Web.json';
import eSurge from 'events/2015-September-United States-MD-National Harbor-Surge.json';
import eSwetugg2018 from 'events/2018-February-Sweden-unknown-stateProvince-Stockholm-Swetugg 2018.json';
import eSwiftSummit from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-Swift Summit.json';
import eSwiftAveiro2017 from 'events/unknown-start-Portugal-unknown-stateProvince-Aveiro-SwiftAveiro 2017.json';
import eSwiftConf from 'events/unknown-start-Germany-unknown-stateProvince-Cologne-SwiftConf.json';
import eSwissPerlspaceWorkshop from 'events/unknown-start-Switzerland-unknown-stateProvince-Bern-Swiss Perl Workshop.json';
import eSwissJS from 'events/unknown-start-Switzerland-unknown-stateProvince-Bern-SwissJS.json';
import eSXSW from 'events/2016-March-United States-TX-Austin-SXSW.json';
import eSyntaxCodespaceandspaceCraftspaceConvention from 'events/unknown-start-United States-SC-Charlseton-Syntax Code & Craft Convention.json';
import eSyScan from 'events/unknown-start-China-unknown-stateProvince-Bejing-SyScan.json';
import eT2dotfi from 'events/unknown-start-Finland-unknown-stateProvince-Helsinki-T2.fi.json';
import eTablelessConference from 'events/2013-May-Brazil-unknown-stateProvince-Sao Paulo-Tableless Conference.json';
import eTechBash2017 from 'events/2017-October-United States-PA-Pocono Manor-TechBash 2017.json';
import eTechDays from 'events/unknown-start-Sweden-unknown-stateProvince-Stockholm-TechDays.json';
import eTechDays from 'events/unknown-start-The Netherlands-unknown-stateProvince-The Hague-TechDays.json';
import eTechEd from 'events/2015-May-United States-TX-Houston-TechEd.json';
import eTechonomy from 'events/unknown-start-United States-AZ-Tucson-Techonomy.json';
import eTechoramaBelgium from 'events/unknown-start-Belgium-unknown-stateProvince-Brussels-Techorama Belgium.json';
import eTexasLinuxFest from 'events/2015-August-United States-TX-Austin-Texas LinuxFest.json';
import eTexasJS from 'events/unknown-start-United States-TX-Austin-TexasJS.json';
import eThatConference from 'events/unknown-start-United States-WI-Wisconson Dells-That Conference.json';
import eTHCon from 'events/unknown-start-France-unknown-stateProvince-Toulouse-THCon.json';
import eTHECONF from 'events/2017-September-Brazil-São Paulo-São Paulo-THE CONF.json';
import eTheEmailspaceDesignspaceConference from 'events/unknown-start-United Kingdom-unknown-stateProvince-London-The Email Design Conference.json';
import eTheGeekspaceGathering from 'events/2014-May-Croatia-unknown-stateProvince-Osijek-The Geek Gathering.json';
import eTheRollingspaceScopes from 'events/unknown-start-Belarus-unknown-stateProvince-Minsk-The Rolling Scopes.json';
import eThingMonk from 'events/2015-December-United Kingdom-unknown-stateProvince-London-ThingMonk.json';
import eThotCon from 'events/unknown-start-United States-IL-Chicago-ThotCon.json';
import eTHREADS from 'events/2014-November-United States-NY-Brooklyn-THREADS.json';
import eThunderPlains from 'events/2017-November-United States-OK-Oklahoma City-Thunder Plains.json';
import eTNW from 'events/2015-November-United States-NY-New York-TNW.json';
import eTroopers from 'events/unknown-start-United States-MI-Heidelberg-Troopers.json';
import eTrueNorthspacePHP from 'events/2014-November-Canada-ON-Toronto-True North PHP.json';
import etrybangSwiftspaceBangalore from 'events/unknown-start-India-unknown-stateProvince-Bangalore-try! Swift Bangalore.json';
import etrybangSwiftspaceNewspaceYork from 'events/unknown-start-United States-NY-New York-try! Swift New York.json';
import etrybangSwiftspaceTokyospace2017 from 'events/unknown-start-Japan-unknown-stateProvince-Tokyo-try! Swift Tokyo 2017.json';
import eTulsaTechspaceFest from 'events/unknown-start-United States-OK-Tulsa-Tulsa Tech Fest.json';
import eTwinCitiesspaceCodespaceCamp from 'events/unknown-start-United States-MN-Minneapolis-Twin Cities Code Camp.json';
import eUIKonf from 'events/unknown-start-Germany-unknown-stateProvince-Berlin-UIKonf.json';
import eUniversalJSspaceDay from 'events/unknown-start-Italy-unknown-stateProvince-Ferrara-Universal JS Day.json';
import eUniversityofspaceIllinoisspaceWebspaceConference from 'events/2018-April-United States-IL-Champaign-University of Illinois Web Conference.json';
import eUplinq from 'events/2015-September-United States-CA-San Francisco-Uplinq.json';
import eUSENIXSecurity from 'events/unknown-start-Canada-BC-Vancouver-USENIX Security.json';
import eUSENIXWOOT from 'events/unknown-start-Canada-BC-Vancouver-USENIX WOOT.json';
import eUtahJS from 'events/unknown-start-United States-UT-Salt Lake City-UtahJS.json';
import eUXBurlington from 'events/unknown-start-United States-VT-Burlington-UX Burlington.json';
import eUXPoland from 'events/2014-April-Poland-unknown-stateProvince-Warsaw-UX Poland.json';
import eUXSingapore from 'events/unknown-start-Singapore-unknown-stateProvince-Singapore-UX Singapore.json';
import eUXLx from 'events/2015-June-Portugal-unknown-stateProvince-Lisbon-UXLx.json';
import eVelocity from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-Velocity.json';
import eVelocity from 'events/2014-September-United States-NY-New York-Velocity.json';
import eVirusBulletin from 'events/unknown-start-Spain-unknown-stateProvince-Madrid-Virus Bulletin.json';
import eVisualStudiospaceLivebang from 'events/unknown-start-United States-DC-Washington-Visual Studio Live!.json';
import eVisualStudiospaceLivebang from 'events/unknown-start-United States-FL-Orlando-Visual Studio Live!.json';
import eVisualStudiospaceLivebang from 'events/unknown-start-United States-NV-Las Vegas-Visual Studio Live!.json';
import eVisualStudiospaceLivebang from 'events/2015-September-United States-NY-New York-Visual Studio Live!.json';
import eVSLiveChicago from 'events/2017-September-United States-IL-Chicago-VSLive Chicago.json';
import eVueConf from 'events/unknown-start-Poland-unknown-stateProvince-Wrocław-VueConf.json';
import eW3CBrazilspaceConference from 'events/unknown-start-Brazil-unknown-stateProvince-Sao Paulo-W3C Brazil Conference.json';
import eWAHCKon from 'events/unknown-start-Australia-unknown-stateProvince-Perth-WAHCKon.json';
import eWarCon from 'events/unknown-start-Poland-unknown-stateProvince-Warsaw-WarCon.json';
import eWDCNZ from 'events/2015-July-New Zealand-unknown-stateProvince-Wellington-WDCNZ.json';
import eWeaponsofspaceMassspaceCreationspaceFestival from 'events/unknown-start-United States-OH-Cleveland-Weapons of Mass Creation Festival.json';
import eWebaspaceQuebec from 'events/2015-March-Canada-QC-Quebec-Web a Quebec.json';
import eWebDirectionsspaceCode from 'events/unknown-start-Australia-unknown-stateProvince-Melbourne-Web Directions Code.json';
import eWebDirectionsspaceSouth from 'events/unknown-start-Australia-unknown-stateProvince-Sydney-Web Directions South.json';
import eWebRebelsspaceConf from 'events/2015-May-Norway-unknown-stateProvince-Oslo-Web Rebels Conf.json';
import eWebSummerspaceCamp from 'events/unknown-start-Croatia-unknown-stateProvince-Rovinj-Web Summer Camp.json';
import eWebSummit from 'events/2015-November-Ireland-unknown-stateProvince-Dublin-Web Summit.json';
import eWebUnleashed from 'events/2014-September-Canada-ON-Toronto-Web Unleashed.json';
import eWebdagene from 'events/2017-October-Norway-Oslo-Oslo-Webdagene.json';
import eWebDevConf from 'events/unknown-start-United Kingdom-unknown-stateProvince-Bristol-WebDevConf.json';
import eWebExpo from 'events/2015-September-Czech Republic-unknown-stateProvince-Prague-WebExpo.json';
import eWebExpo from 'events/2017-September-Czech Republic-unknown-stateProvince-Prague-WebExpo.json';
import ewebRTC from 'events/2015-May-United States-FL-Miami-webRTC.json';
import eWebstock from 'events/2014-February-New Zealand-unknown-stateProvince-Wellington-Webstock.json';
import eWebtech from 'events/unknown-start-Germany-unknown-stateProvince-Munich-Webtech.json';
import eWebVisions from 'events/unknown-start-United States-OR-Portland-WebVisions.json';
import eWindyCityRails from 'events/2015-September-United States-IL-Chicago-WindyCityRails.json';
import eWiSec from 'events/unknown-start-United States-MA-Boston-WiSec.json';
import eWordCampColombo from 'events/unknown-start-Sri Lanka-Western-Colombo-WordCamp Colombo.json';
import eWordCampManchester from 'events/2015-June-United Kingdom-unknown-stateProvince-Manchester-WordCamp Manchester.json';
import eWPTech from 'events/unknown-start-France-unknown-stateProvince-Nantes-WP Tech.json';
import eWritefwslashSpeakfwslashCode from 'events/unknown-start-United States-NY-New York-WriteSpeakCode.json';
import eWWDC from 'events/2015-June-United States-CA-San Francisco-WWDC.json';
import eXamarinEvolve from 'events/2016-April-United States-FL-Orlando-Xamarin Evolve.json';
import exdacolondevcon from 'events/2014-September-United Kingdom-unknown-stateProvince-Manchester-xdadevcon.json';
import eXebiCon from 'events/unknown-start-The Netherlands-unknown-stateProvince-Amsterdam-XebiCon.json';
import eXOXO from 'events/2015-September-United States-OR-Portland-XOXO.json';
import eYAPC from 'events/2015-September-Brazil-unknown-stateProvince-Taubat-YAPC.json';
import eYAPC from 'events/unknown-start-Ukraine-unknown-stateProvince-Kiev-YAPC.json';
import eYosemitebyspaceCocoaConf from 'events/unknown-start-United States-CA-Yosemite National Park-Yosemite by CocoaConf.json';
import eYouGottaspaceLovespaceFrontend from 'events/unknown-start-Israel-unknown-stateProvince-Tel Aviv-You Gotta Love Frontend.json';
import eYouShotspaceThespaceSheriff from 'events/unknown-start-Brazil-unknown-stateProvince-Sao Paulo-You Shot The Sheriff.json';
import eYowConference from 'events/unknown-start-Austrailia-unknown-stateProvince-Brisbane-Yow Conference.json';
import eYowConference from 'events/unknown-start-Austrailia-unknown-stateProvince-Melbourne-Yow Conference.json';
import eYowConference from 'events/unknown-start-Austrailia-unknown-stateProvince-Sydney-Yow Conference.json';
import eZendcon from 'events/unknown-start-United States-NV-Las Vegas-Zendcon.json';
import eZeroNights from 'events/unknown-start-Russia-unknown-stateProvince-Moscow-ZeroNights.json';
import eØredev from 'events/2015-November-Sweden-unknown-stateProvince-Malmö-Øredev.json';


export default [ebangbangCon,edotconcatparensparens,edotNETConfspaceUY,e200OK,e2017atSwift,e34C3,e360iDev,e44Con,ecolonclojured,eatdatanativesconf,eA2Ydotasm,eAccessibilitySummit,eACE,eACMCCS,eActiveIngredients,eAdaCamp,eAdobeMAX,eAfricaHackon,eAgentConference,eAgile2015,eAgileDevspacePractices,eAgileIndia,eAgileSpain,eAgileTestingspaceDays,eAIMUtahspaceCIOspaceSummit,eAllThingsspaceOpen,eAllYourspaceBasespaceConf,eAlliedMediaspaceConference,eAlterConf,eAmsterdamJS,eAnEventspaceApart,eAnDevCon,eAndroidSecurityspaceSymposium,eandyetconf,eAngularCamp,eAngularCruise,eAngularMix,eAngularConnect,eAngularUP,eApacheCon,eAPIStrategy,eAPIWorld,eAPIdays,eAPIdays,eAppBuildersspaceSwitzerland,eAppDesignspaceandspaceDevelopmentspaceConference,eAppdevcon2017,eArtifactConference,easiabsdcon,eAtlassianSummit,eAtlSecCon,eATypI,eAUSTINGAMEspaceCONFERENCE,eAVAR,eAWSRecolonInvent,eAWSrecoloninvent,eBackboneConf,eBADCamp,eBASTAbang,eBeyondTellerrand,eBeyondThespaceDesktop,eBI2015,eBigDataspaceConference,eBigDataspaceConference,eBigDesignspaceConference,eBigRubyspaceConf,eBigConf,eBlackHat,eBlackHatAsia,eBlackHatEU,eBlackHatUS,eBlendConference,eBlendWebspaceMix,eBlockchainandspaceCryptocurrencyspaceConspace2018,eBooksinspaceBrowsers,eboostparensjsparens,eBooster,eBornhack,eBostonCodespaceCamp,eBotConf,eBoxWorks,eBrazilJSspaceConf,eBrazilJS,eBrick2014,eBritishnodespaceconf,eBrooklynJS,eBruCon,ebsdcan,eBSidesCanberra,eBSidesLjubljana,eBSidesMunichatBSidesMunich,eBudapestNodeConfspace2017,eBuildstufflithuania,eBulgariaWebspaceSummit,eBusinessofspaceSoftwarespaceConference,eBuzzJS,eBytesConf,eCakeFest,eCAMPFestival,eCampJS,eCanSecWest,ecanvas,eCapitolJS,eCardis,eCARO,eCascadiaFest,eCascadiaJS,eCasITConf,eCassandraSummit,eCentralWisconsinspaceITspaceConference,eChainReactspace2017,eChefConf,eCHES,eChippewaValleyspaceCodespaceCamp,eChromeDevspaceSummitspace2017,eCircleCityCon,eCircumventionTechspaceFestival,eClarity,eClojurefwslashWest,eCloudExpo,eCloudBrew2017,eCloudDevelopConf,eCloudPlugFest,eCMXSummit,eCocoaLove,eCocoaConf,eCocoaConfChicagospace2017,eCocoaLove,eCode,eCodeMotion,eCodeonspacethespaceBeach,eCodePaLOUsa,eCodebits,eCodemania,eCodeMash,eCodemotion,eCodemotion,eCodePaLOUsa,eCoderCruise,eCodestock,eColdFront,ecoldfrontconf,eCollisionConf,eCommunityLeadershipspaceSummit,eConfabIntensive,eConferenceforspacethespaceAssociationspaceofspaceSoftwarespaceTesting,eConfidence,eConfitura,eConFooMontreal,eConFooVancouver,eCONFRONT,eConnectdotjs,eConnectdotTech,eConnections,eConnectJS,eContainerCamp,eContinuousLifecyclespaceConference,eConvergeSE,eCopenhagenContext,ecopenhagenjs,eCornerstone,eCouchbaseLive,ecppcon,eCraftConference,eCreateUpstate,eCrikeyCon,eCSSDay,eCSSDevspaceConf,eCSSMinskdashJSConf,ecssfwslashsassconference,eCSSConf,eCSSConf,eCSSConfAU,eCSSConfAustralia,eCSSConfBudapest,eCSVConf,eCukeUp,eDaFED,eDataDayspaceTexasspace?,edConstruct,eDecolonCode,eDeeperLifespaceHolidayspaceschool,eDeepSec,eDefCamp,eDEFCON,eDenverDevspaceDay,eDesertCodespaceCamp,eDesignerofspaceThings,eDeSymfony,eDevConf,eDevConnections,eDevDay,eDeveloperWeekspaceConf,eDeveloperWeekJavaScriptspaceConference,eDevExperiencedotro,eDevIntersection,eDEVitWebspaceConference,edevLink,eDevNexus,eDevOpsDays,eDevopsDays,eDevopsDays,eDevoxxBE,eDevoxxMA,eDevoxxPL,eDevoxxUK,eDevRelCon,eDevsLobespaceBaconspace2014,eDevSpace,eDevSum,eDevUp,eDevWeek,edevworld,eDigitalBookspaceWorld,eDIMVA,eDinosaurjs,eDisruptSF,eDistill,eDistill2014,eDjangoCon,eDjangoCon,eDjangoConEurope,eDjangoVillage,eDLDConference,eDNNSummit,eDockerCon,eDogFoodCon,eDotAll,edotswift,edotCSS,edotGo,edotJS,edotScale,edotSwift,eDreamforce,eDroidcon,eDroidconLondon,eDroidconNYC,eDroidconSF,eDroidconStockholm,eDrupalCamp,eDrupalCon,eDrupalCon,eDrupalCon,eDutchPHPspaceConference,eeSAMEdashspaceCTFspaceonspaceNovspace30,eEARLparensEffectivespaceApplicationsspaceofspaceRspaceLanguageparens,eebookcraft,eEclipseCon,eEclipseCon,eeCrime,eEdgeConference,eEdgeConf,eEICAR,eElementsPennspaceState,eElixirwithspaceLove,eElixirConf,eEmberFest,eEmberConf,eEmberFest,eEmpireConf,eEmpireNode,eEmpireJS,eEmpireNode,eEndpoint,eENIGMA,eEnterJS,eEpicFEL,eErlangConference,eESORICS,eEuroBSDcon,eEurocrypt,eEuroIA2014,eEuroPython,eEuRuKo,eEuRuKo,eEvernoteConference,eExtensibleWebspaceSummit,eF5Festival,eF8,eFailCon,eFalsyValues,effconf,eFIRSTFare,eFISL,eFITC,eFlight,eFlossSpringspace2014,eFluent,eFormFunctionspaceandspaceClassspace8,eForwardJS,eForwardSwift,eForwardJS,eFOSDEM,eFOSS4G,eFOSSETCON,eFOWD,eFrankfurtBookfair,eFrenchKit,eFrontEndspaceDesignspaceConference,eFrontEndspaceDesignspaceConference,eFrontinspaceBH,eFrontPorch,eFrontTrends,eFrontEndCarioca,efrontendconference,eFrontEndConference,eFrontTrends,eFronteers2014,eFronteersConference,eFRONTENDCONspace2017,eFrontendConferencespaceZurich,eFrontendDevspaceConfspace2017,eFrontendNE,eFrontendUnited,eFrontenders,eFrontFest,eFrontInterior,eFrontTalks,eFrOSCon,eFrozenRails,eFullFrontal,eFullStackspaceConf,eFullStackspaceConf,eFullStackspaceFest,eFullStackspaceToronto,eFullStack,eFunctionalConfspaceIndia,eFunctionalSwiftspaceConferencespace2017,eFunctions17,eFutureInsights,eFutureJS,eFutureofspaceWebspaceApps,eFutureofspaceWebspaceApps,eFutureofspaceWebspaceDesign,eFutureofspaceWebspaceDesignspaceparensthespaceBreweryparens,eFutureStack,eGameDevelopersspaceConference,eGartnerApplicationspaceArchitecture,eGDC,eGDC,eGDCChina,eGDCNext,eGeeCON,eGeekGirlCamp,eGGDevCon,eGIDS,eGlobalInnovationspaceForum,eGluecon,eGoGaRuCo,eGoogleIfwslashO,eGoogleTestspaceAutomation,eGopherCon,eGoto,eGOTO,eGR8Conf,eGraceHopperspaceCelebrationspaceofspaceWomenspaceinspaceComputing,eGraphLab,eGreach2014,eGreHack,eGrrCON,eGWTdotcreate,eHackinspaceParis,eHackinspacethespacebox,eHackdotlu,eHackference,eHackfest,eHacktivity,eHadoopSummit,eHadoopWorld,eHalfStack,eHardweardotio,eHaskellSymposium,eHeartlandDevspaceConference,eHighEdWeb,eHolyJS,eHolyJSMoscow,eHowInteractivespaceDesign,eHTML5DevspaceConf,eHTML5DevConf,eHybridConf,eILovespaceAPIs,eIBMEnterprise2014,eIEEESandP,eiJSInternationalspaceJavaScriptspaceConference,eInsomnisquotehack,eINSTINT,eIntelIDF14,eInterConAndroid,eInternetofspaceThingsspaceForumspace2014,eiOSCon2017,eiOSDCJapanspace2017,eiOSDevUk,eIoTSecurityspaceSummit,eIoTWorldspaceForum,eIowaCodespaceCamp,eItcampspaceRomania,eITWeekend,eITfwslashDevConnections,eJavaLand,eJavaOne,eJavaScriptConference,eJavascriptDay,eJavaZone,eJazoon,eJazzCondotTech,eJFall,eJfokus,eJoyofspaceCoding,ejQueryConf,ejQueryConf,ejQueryConference,ejQueryDevspaceSummit,eJQueryUK,ejQueryConf,eJSDay,eJSfwdays,eJSHeroes,eJSKongress,eJSPoland,eJSRemotespaceConf,eJSChannel,eJSConf,eJSConfBudapest,eJSConfChina,eJSConfColombia,eJSConfEU,eJSConfUS,ejsconfdotbe,eJSConfAsia,eJSConfAU,eJSCONFCo,eJSConfUY,eJSDayItaly,eJSDC,eJSFest,ejsfoo,eJSFooIndia,eJSinSA,ejsist,eJSUnconf,eKalamazooX,eKCDC,eKiwicon,eKiwiParty,eLanuitspaceduspacehack,eLARubyConf,eLambdaWorld,eLatinoware,eLCA,eLeanDayspaceLondonspaceparensLSOspaceShoreditchparens,eLeanStartupspaceConference,eLesbiansWhospaceTech,eLeWeb,eLibertyJS,eLinuxTag,eLISAConference,eLoneStarspacePHP,eLuceneRevolution,eMAwomensquotesspaceconference,eMacAdminspaceandspaceDeveloperspaceConferencespaceUK,eMacAdmins,eMacworld,eMadisonPHP,eMadison+Ruby,eMagentoImagine,eMagmaConf,eMakerFairespaceNewcastle,eMakingWeb,eMALWARE,eManhattanJS,eMCE,eMedellinJS,emediaconventionparenspartspaceofspacerecolonpublicaparens,eMicrosoftIgnite,eMicrosoftMVPspaceSummit,eMidwestGamespaceDevspaceExpo,eMidwestJS,eMidwestPHP,eMidwestTechspaceFest,eMidwestdotio,eMidwestJS,eMidwestUX,eMilwaukeeCodespaceCamp,eMinnesotaDevelopersspaceConference,eMirrorConfspace2017,eMobileDevspaceSummit,eMobileEra,eMobileWebDevConf,eModernWebspaceConf,eMonashUniversity,eMonitorama,eMonktoberfest,eMoonshotCon,eMoscowJS,eMountainWestJavaScript,eMozFest,eMtnWestJS2015,eMusicCityspaceCode,eNAB,eNationJS,eNCDevCon,eNDC,eNDCLondon,eNDCOslo,eNDCSydney,eNDSS,eNebraskadotCodeparensparens,eNebraskaJS,eNEJSCONF,eNetConfdotUY,eNetSecureDay,eNewDirectionsspaceinspaceOperatingspaceSystems,eNewYorkspaceCityspaceCodespaceCamp,eNGEuropespaceparensAngularJSparens,eNGBE,eNGConf,eNGNL,engAtlanta,enginxdotconf,engPoland,engVikings,eNodeInteractive,eNodedotjsInteractivespaceNorthspaceAmerica,enodeconf,eNodeConfArgentina,eNodeConfBarcelona,eNodeConfEurope,eNodeConfEU,eNodeSummit,eNodevember,eNodevember,eNOPCon,eNordicJS,eNorthBayspacePython,eNoSQLNow,eNotFluffJustStuff,eNullCon,eNYCCodespaceCamp,eNYCCamp,eOsquoteReillyarchspaceconf,eOsquoteReillyFluent,eOsquoteReillyOSCONspaceAustin,eOaklandJS,eOculusConnect,eOdessaJS,eOggCamp,eOhioLinuxFest,eOOP,eOpenSourcespaceandspaceFeelings,eOpenWebspaceCamp,eOpenCon,eOpenFest,eOpenStackSummit,eOpenVisConf,eOpenWest,eOracleOpenspaceWorld,eOSBridge,eOSCon,eOSCON,eOSDC,eParanoia,eParisWeb,ePechaKucha,ePhDays,ephpConferencespaceArgentina,ePHPCraft,ePHPDay,ePHPBenelux,ePHPNWManchester,ePHPUK,ePinkElephant,ePipelineConf,epitercss,ePlaygrounds,ePLIBMTTBHGATY,ePluralsightAuthorspaceSummit,ePNWScala,ePolyConf,ePolyconf2014,ePostgresConference,ePostgresOpen,ePragmaConference,ePrairieCode,ePrairieDevspaceCon,ePrairiedotCodeparensparens,ePressnomics,ePuppetConf,ePuppetconf,ePyCon,ePyConArgentina,ePyConAU,ePyConFI,ePyconFR,ePyConIreland,ePyconPL,ePyconUK,ePyConUruguay,ePyData,ePyGotham,ePyOhio,ePyTennessee,ePyTexas,eQcon,eQcon,eQcon,eQcon,eQCon,eQcon,eQcon,er2con,eRailsConf,eRailsconf,eRailsconf,eRailsGirlsAmsterdam,eRedotWorkInternetspaceofspaceThings,erecolonpublica,eReactparensShoreditchspaceWorksspaceVillagespaceHallparens,eReactAlicante,eReactAmsterdam,eReactBoston,eReactConf,eReactConfspaceBrasil,eReactDayspace2017,eReactDayspaceBerlin,eReactEurope,eReactLondon,eReactNativespaceEU,eReactRally,eReactConfEU,eReactEurope,eReactFoo,eReactiveConf,eReactiveConf,eReactJSDay,eReactNext,eReactRally,eRealtimeConfEU,eRecon,eRecurseCenter,eRedDotRubyConf,eRefresh,eRefreshOttawa,eRejectdotjs,eRender,eRESTFEST,eRevolutionConf,eRigaDevspaceDays,eRMLLSecurityspacetrack,eRobotsConf,eRootedCon,eRSAconference,eRubyConf,eRubyConfArgentina,eRubyConfAU,eRubyConfBrasil,eRubyConfColombia,eRubyConfUruguay,eRubyslava,eRuhrJS,eRuhrSec,eRuLu,eRuxcon,eRVAJavaScript,eRWDevCon,eSaltConf17,eSaminaireAccessiweb,eSamsungDeveloper,eSAS,eSaSeIoT,eSassConf,eScalaByspaceThespaceBay,eScalaDays,eScalaIO,eScalaUnderscore,eSCALE16xspacespace16thspaceAnnualspaceSouthernspaceCaliforniaspaceLinuxspaceExpo,eScotlandjs,eScottishRubyspaceConf,eScript,eSeaGL,eSeattleJS,eSecT,eSecITC,eSecTor,eSecuriTay,eSecurityofspaceThingsspaceWorld,eSFPCSalon,eSHA2017,eSharePointFestspaceChicago,eSharkFestsquote17spaceEurope,eShe’sGeeky,eShmooCon,eSiliconValleyspaceCodespaceCamp,eSIMBig,eSmallisspaceBeautiful,eSmartTravel,eSmashingConfSanspaceFrancisco,eSmidig,eSoEmber,eSocialConnections,eSoftwareArchitecture,eSoftwareDesignspaceandspaceDevspaceparensSDDparens,eSolid,eSourceUpbang,eSouthEastLinuxFest,eSoutheastRuby,eSpaceCityspaceJS,eSplunkdotconf2014,eSpringOne2GX,eSRCCON,eSSTIC,eStarsConf2017,eStartupGrind,eStateofspacethespaceMapspaceUS,eSteelCon,eStirTrek,eStpcon,eStrangeloop,eStrataConf,eStrataConf,eSudWeb,eSurge,eSwetugg2018,eSwiftSummit,eSwiftAveiro2017,eSwiftConf,eSwissPerlspaceWorkshop,eSwissJS,eSXSW,eSyntaxCodespaceandspaceCraftspaceConvention,eSyScan,eT2dotfi,eTablelessConference,eTechBash2017,eTechDays,eTechDays,eTechEd,eTechonomy,eTechoramaBelgium,eTexasLinuxFest,eTexasJS,eThatConference,eTHCon,eTHECONF,eTheEmailspaceDesignspaceConference,eTheGeekspaceGathering,eTheRollingspaceScopes,eThingMonk,eThotCon,eTHREADS,eThunderPlains,eTNW,eTroopers,eTrueNorthspacePHP,etrybangSwiftspaceBangalore,etrybangSwiftspaceNewspaceYork,etrybangSwiftspaceTokyospace2017,eTulsaTechspaceFest,eTwinCitiesspaceCodespaceCamp,eUIKonf,eUniversalJSspaceDay,eUniversityofspaceIllinoisspaceWebspaceConference,eUplinq,eUSENIXSecurity,eUSENIXWOOT,eUtahJS,eUXBurlington,eUXPoland,eUXSingapore,eUXLx,eVelocity,eVelocity,eVirusBulletin,eVisualStudiospaceLivebang,eVisualStudiospaceLivebang,eVisualStudiospaceLivebang,eVisualStudiospaceLivebang,eVSLiveChicago,eVueConf,eW3CBrazilspaceConference,eWAHCKon,eWarCon,eWDCNZ,eWeaponsofspaceMassspaceCreationspaceFestival,eWebaspaceQuebec,eWebDirectionsspaceCode,eWebDirectionsspaceSouth,eWebRebelsspaceConf,eWebSummerspaceCamp,eWebSummit,eWebUnleashed,eWebdagene,eWebDevConf,eWebExpo,eWebExpo,ewebRTC,eWebstock,eWebtech,eWebVisions,eWindyCityRails,eWiSec,eWordCampColombo,eWordCampManchester,eWPTech,eWritefwslashSpeakfwslashCode,eWWDC,eXamarinEvolve,exdacolondevcon,eXebiCon,eXOXO,eYAPC,eYAPC,eYosemitebyspaceCocoaConf,eYouGottaspaceLovespaceFrontend,eYouShotspaceThespaceSheriff,eYowConference,eYowConference,eYowConference,eZendcon,eZeroNights,eØredev]